// UPDATE 5 — privacy, referrals, rate limits, SMS, push, verification, photos, disputes, reports, blocks, feedback,
// payment details, wildlife, offices, officer Q&A, yields, subsidies, support prices, damage reports, rain planner,
// printable reports, district impact and system health. Real HTTP + a mock SMS gateway + a real database.
const assert = require("assert"); const mongoose = require("mongoose"); const http_ = require("http"); const jwt = require("jsonwebtoken");
const BASE = "http://127.0.0.1:5055/api"; let passed = 0; const ok = (m) => console.log(`  ok ${++passed}. ${m}`);
async function http(method, path, { token, body, raw } = {}) {
  const res = await fetch(BASE + path, { method, headers: { ...(token ? { Authorization: "Bearer " + token } : {}), ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined });
  if (raw) return res; const text = await res.text(); let json = null; try { json = JSON.parse(text); } catch (_) {} return { status: res.status, body: json, text };
}
const login = async (email, password = "Demo@1234") => { const r = await http("POST", "/auth/login", { body: { email, password } }); assert.equal(r.status, 200, email + " " + r.text); return { token: r.body.data.token, id: r.body.data.user.id }; };
const PNG = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";
const N = (i) => `neighbour${i}@neighbour.demo.agrilink.lk`;
const inHours = (h) => new Date(Date.now() + h * 3600000).toISOString();
const KANDY = { latitude: 7.2906, longitude: 80.6337 };

(async () => {
  const M = (n) => require("./models/" + n);
  const User = M("User"), Reminder = M("Reminder"), Listing = M("MarketplaceListing"), Photo = M("Photo"), LedgerEntry = M("LedgerEntry"), YieldRecord = M("YieldRecord"), SmsLog = M("SmsLog"), DeviceToken = M("DeviceToken"), ErrorLog = M("ErrorLog"), RainfallCache = M("RainfallCache"), PaymentProfile = M("PaymentProfile"), MarketPrice = M("MarketPrice");
  await mongoose.connect("mongodb://127.0.0.1:27017/agrilink_e2e");
  // mock SMS gateway on :5099 — records exactly what the server sends
  const smsHits = []; const smsServer = http_.createServer((req, res) => { let b = ""; req.on("data", (c) => (b += c)); req.on("end", () => { smsHits.push({ auth: req.headers.authorization, body: JSON.parse(b) }); res.writeHead(200); res.end("{}"); }); }); await new Promise((r) => smsServer.listen(5099, r));
  const liveIds = (await User.find({}).select("_id").lean()).map((u) => u._id);
  await MarketPrice.deleteMany({ source: "admin", isDemo: { $ne: true }, reporter: { $nin: liveIds } });
  await User.deleteMany({ email: { $in: ["admin.v5@agrilink.lk", "delete.me@test.lk"] } }); await User.deleteMany({ email: /@deleted\.invalid$/ });
  await User.create({ fullName: "Admin V5", email: "admin.v5@agrilink.lk", phone: "+94770000025", passwordHash: await User.hashPassword("Admin@1234"), role: "admin" });
  const F = await login("demo.farmer@agrilink.lk"), B = await login("demo.buyer@agrilink.lk"), B2 = await login("buyer2@neighbour.demo.agrilink.lk"), D = await login("demo.driver@agrilink.lk"), ADMIN = await login("admin.v5@agrilink.lk", "Admin@1234");
  const F1 = await login(N(1)), F2 = await login(N(2)), F3 = await login(N(3)), F4 = await login(N(4)), F9 = await login(N(9)), F12 = await login(N(12));
  await http("PATCH", "/auth/me", { token: F1.token, body: { farmerProfile: { district: "Kandy" } } }); await http("PATCH", "/auth/me", { token: F2.token, body: { farmerProfile: { district: "Kandy" } } });
  ok("logged in: demo farmer, 2 buyers, driver, admin and 6 neighbour farmers");

  // ================= PRIVACY / CONSENT / EXPORT / DELETE =================
  const pv = await fetch(BASE + "/legal/privacy"); const pvText = await pv.text(); assert.equal(pv.status, 200); assert.match(pv.headers.get("content-type"), /html/); assert.ok(pvText.includes("AgriLink privacy notice") && pvText.includes('lang="si"') && pvText.includes('lang="ta"') && pvText.includes("delete your account")); ok("the privacy notice is a public web page in English, Sinhala and Tamil");
  const ver = await http("GET", "/app/version"); assert.equal(ver.status, 200); assert.ok(ver.body.data.minVersion && ver.body.data.privacyVersion); ok("public app-version endpoint tells old apps the minimum version");
  assert.equal((await http("POST", "/auth/consent", { body: { version: "x" } })).status, 401); assert.equal((await http("POST", "/auth/consent", { token: F12.token, body: { version: "2026-09" } })).status, 200); const f12 = await User.findById(F12.id); assert.ok(f12.consentAcceptedAt); assert.equal(f12.consentVersion, "2026-09"); ok("accepting the privacy notice is recorded with its version and time");
  const code1 = (await http("GET", "/auth/referrals", { token: F1.token })).body.data; assert.match(code1.code, /^[A-Z2-9]{6}$/); assert.equal((await http("GET", "/auth/referrals", { token: F1.token })).body.data.code, code1.code); ok(`every account gets a stable 6-character referral code (${code1.code})`);
  const reg = await http("POST", "/auth/register", { body: { fullName: "Delete Me", email: "delete.me@test.lk", phone: "0771112222", password: "Passw0rd!", role: "farmer", referralCode: code1.code.toLowerCase(), farmerProfile: { district: "Kandy" } } }); assert.equal(reg.status, 201); const DM = { token: reg.body.data.token, id: reg.body.data.user.id };
  assert.equal((await http("GET", "/auth/referrals", { token: F1.token })).body.data.invited, 1); assert.equal((await http("GET", "/auth/referrals", { token: DM.token })).body.data.invited, 0); assert.match((await http("GET", "/auth/referrals", { token: DM.token })).body.data.code, /^[A-Z2-9]{6}$/); ok("a new farmer who types F1's code (any letter case) is counted as F1's referral and gets their own code");
  const board = await http("GET", "/admin/referrals", { token: ADMIN.token }); assert.ok(board.body.data.some((r) => r.code === code1.code && r.total === 1 && r.farmers === 1)); assert.equal((await http("GET", "/admin/referrals", { token: F.token })).status, 403); ok("the admin sees a referral leaderboard (farmers only)");
  await http("POST", "/ledger", { token: DM.token, body: { type: "expense", category: "seeds", amountLkr: 500 } }); await http("POST", "/records/yields", { token: DM.token, body: { cropType: "Tomato", season: "yala", year: 2026, acres: 1, harvestKg: 1000 } });
  const ex = await http("GET", "/auth/export", { token: DM.token, raw: true }); const exJson = JSON.parse(await ex.text()); assert.equal(ex.status, 200); assert.match(ex.headers.get("content-disposition"), /attachment/); assert.equal(exJson.account.email, "delete.me@test.lk"); assert.equal(exJson.account.passwordHash, undefined); assert.equal(exJson.ledger.length, 1); assert.equal(exJson.yields.length, 1); ok("'download my data' returns a file with my account, ledger and harvest records — and never the password hash");
  assert.equal((await http("POST", "/auth/delete-account", { token: DM.token, body: { password: "wrong" } })).status, 401); assert.equal((await http("POST", "/auth/delete-account", { token: ADMIN.token, body: { password: "Admin@1234" } })).status, 403);
  const oL = await Listing.create({ farmer: DM.id, cropType: "Tomato", quantityKg: 10, originalPricePerKg: 100, currentPricePerKg: 100, harvestDate: new Date(), qualityGrade: "A" }); const dmOrder = (await http("POST", "/orders", { token: B.token, body: { listingId: String(oL._id) } })).body.data.id;
  assert.equal((await http("POST", "/auth/delete-account", { token: DM.token, body: { password: "Passw0rd!" } })).body.code, "unfinished_orders"); await http("POST", `/orders/${dmOrder}/cancel`, { token: B.token }); ok("deleting an account needs the password, is refused for admins, and is blocked while an order is unfinished");
  assert.equal((await http("POST", "/auth/delete-account", { token: DM.token, body: { password: "Passw0rd!" } })).status, 200); const gone = await User.findById(DM.id); assert.equal(gone.fullName, "Deleted user"); assert.equal(gone.phone, ""); assert.equal(gone.isActive, false); assert.match(gone.email, /@deleted\.invalid$/); assert.equal(await LedgerEntry.countDocuments({ farmer: DM.id }), 0); assert.equal(await YieldRecord.countDocuments({ farmer: DM.id }), 0); assert.equal(await Listing.countDocuments({ farmer: DM.id }), 0); assert.equal((await http("POST", "/auth/login", { body: { email: "delete.me@test.lk", password: "Passw0rd!" } })).status, 401); ok("account deleted: name, phone and email erased, ledger / harvest records / open listings removed, login no longer possible");

  // ================= RATE LIMITING, ERROR LOG (unit level) =================
  const { limiter, loginGuard, requestLogger } = require("./middleware/rateLimit");
  const mkRes = () => { const h = {}; return { headers: h, statusCode: 200, on(ev, fn) { (this.fns = this.fns || {})[ev] = fn; }, set(k, v) { h[k] = v; }, status(c) { this.statusCode = c; return this; }, json(b) { this.body = b; return this; } }; };
  const lim = limiter({ windowMs: 60000, max: 3 }); const req = { headers: { "x-forwarded-for": "9.9.9.9, 1.1.1.1" }, ip: "::1" }; const results = []; for (let i = 0; i < 5; i++) { const res = mkRes(); let passedThrough = false; lim(req, res, () => (passedThrough = true)); results.push(passedThrough ? 200 : res.statusCode); }
  assert.deepEqual(results, [200, 200, 200, 429, 429]); const other = mkRes(); let otherPassed = false; lim({ headers: { "x-forwarded-for": "8.8.8.8" }, ip: "::1" }, other, () => (otherPassed = true)); assert.ok(otherPassed); ok("the rate limiter lets 3 requests through, blocks the 4th and 5th (429), and counts each address separately");
  const guard = loginGuard({ max: 3 }); const lreq = { headers: { "x-forwarded-for": "7.7.7.7" }, body: { email: "a@b.lk" }, ip: "::1" }; const outcomes = [];
  for (let i = 0; i < 5; i++) { const res = mkRes(); let next = false; guard.check(lreq, res, () => (next = true)); if (next) { res.statusCode = 401; res.fns.finish(); outcomes.push("tried"); } else outcomes.push(res.statusCode); }
  assert.deepEqual(outcomes, ["tried", "tried", "tried", 429, 429]); const good = mkRes(); let gn = false; guard.check({ headers: { "x-forwarded-for": "6.6.6.6" }, body: { email: "z@b.lk" }, ip: "::1" }, good, () => (gn = true)); assert.ok(gn); ok("login brute-force guard: after 3 WRONG passwords the 4th try is blocked; a different person is unaffected");
  const guard2 = loginGuard({ max: 2 }); const g2 = { headers: {}, body: { email: "ok@b.lk" }, ip: "5.5.5.5" }; for (const status of [401, 200, 401, 200, 401]) { const res = mkRes(); let n = false; guard2.check(g2, res, () => (n = true)); assert.ok(n, "should not be blocked"); res.statusCode = status; res.fns.finish(); } ok("a correct login resets the count, so a real farmer who mistypes now and then is never locked out");
  const before = await ErrorLog.countDocuments({}); const lr = mkRes(); requestLogger({ method: "GET", originalUrl: "/api/x?secret=1", url: "/api/x" }, lr, () => {}); lr.statusCode = 500; lr.json({ message: "boom" }); lr.fns.finish(); await new Promise((r) => setTimeout(r, 200)); const logged = await ErrorLog.findOne({}).sort({ at: -1 }); assert.equal(await ErrorLog.countDocuments({}), before + 1); assert.equal(logged.status, 500); assert.equal(logged.path, "/api/x"); assert.equal(logged.message, "boom"); const lr2 = mkRes(); requestLogger({ method: "GET", originalUrl: "/api/y", url: "/api/y" }, lr2, () => {}); lr2.statusCode = 404; lr2.fns.finish(); await new Promise((r) => setTimeout(r, 100)); assert.equal(await ErrorLog.countDocuments({}), before + 1); ok("server errors (500) are recorded with the path but not the query string; ordinary 404s are not");
  assert.equal((await http("POST", "/ads/000000000000000000000001/impression")).status !== 429, true); ok("ad tracking calls are rate-limited per address (no inflating numbers)");

  // ================= SMS =================
  await User.updateOne({ _id: F12.id }, { $set: { phone: "0771234567" } }); assert.equal((await http("PATCH", "/auth/me", { token: F12.token, body: { smsAlerts: true } })).status, 200); assert.equal((await User.findById(F12.id)).smsAlerts, true);
  await http("POST", "/prices/alerts", { token: F12.token, body: { cropType: "Carrot", direction: "above", thresholdLkr: 1 } });
  await http("POST", "/admin/prices", { token: ADMIN.token, body: { market: "Kandy", prices: [{ cropType: "Carrot", pricePerKg: 260 }] } }); await new Promise((r) => setTimeout(r, 400));
  assert.equal(smsHits.length, 1); assert.equal(smsHits[0].auth, "Bearer tok"); assert.equal(smsHits[0].body.to, "+94771234567"); assert.match(smsHits[0].body.message, /Carrot/); assert.equal(smsHits[0].body.sender, "AgriLink"); ok("SMS: an opted-in farmer gets ONE text through the gateway, phone normalised to +94771234567, gateway token sent");
  assert.equal(smsHits.filter((h) => h.body.to !== "+94771234567").length, 0); ok("farmers who did not opt in receive no SMS");

  // ================= PUSH (in-process) =================
  const push = require("./utils/push"); const { notifyFarmer } = require("./utils/notify"); const sent = []; push.setSender(async (tokens, msg) => sent.push({ tokens, msg }));
  assert.equal((await push.sendPush(F2.id, { title: "t", body: "b" })).status, "skipped"); assert.equal((await http("POST", "/notifications/device", { token: F2.token, body: { token: "short" } })).status, 400); assert.equal((await http("POST", "/notifications/device", { body: { token: "x".repeat(40) } })).status, 401); assert.equal((await http("POST", "/notifications/device", { token: F2.token, body: { token: "f".repeat(40) } })).status, 200);
  await notifyFarmer(F2.id, { type: "order_update", title: "Push test", message: "hello", dedupeKey: "push-" + Date.now() }); assert.equal(sent.length, 1); assert.deepEqual(sent[0].tokens, ["f".repeat(40)]); assert.equal(sent[0].msg.title, "Push test");
  const dedupe = "push-dup-" + Date.now(); await notifyFarmer(F2.id, { type: "order_update", title: "x", message: "y", dedupeKey: dedupe }); await notifyFarmer(F2.id, { type: "order_update", title: "x", message: "y", dedupeKey: dedupe }); assert.equal(sent.length, 2); await http("DELETE", "/notifications/device", { token: F2.token, body: { token: "f".repeat(40) } }); assert.equal(await DeviceToken.countDocuments({ user: F2.id }), 0); ok("push: phones register a device token; every new notification is pushed once (duplicates are not); tokens can be removed; no phone = skipped");

  // ================= RAIN DATA (in-process, fake weather service) =================
  const rain = require("./utils/rainfall"); await RainfallCache.deleteMany({ district: "Galle" });
  const endYear = new Date().getFullYear() - 1, startYear = endYear - 4; const time = [], precip = [];
  for (let y = startYear; y <= endYear; y++) for (let d = new Date(Date.UTC(y, 0, 1)); d.getUTCFullYear() === y; d = new Date(d.getTime() + 86400000)) { time.push(d.toISOString().slice(0, 10)); precip.push(d.getUTCMonth() === 9 ? 5 : d.getUTCMonth() === 3 ? 3 : 1); }
  let calls = 0; rain.setFetch(async (url) => { calls++; assert.match(url, /archive-api\.open-meteo\.com/); return { ok: true, status: 200, json: async () => ({ daily: { time, precipitation_sum: precip } }) }; });
  const r1 = await rain.monthlyRainfall("Galle"); assert.equal(r1.cached, false); assert.equal(r1.years, 5); assert.equal(r1.monthlyMm[9], 155); assert.equal(r1.monthlyMm[3], 90); assert.equal(r1.monthlyMm[0], 31); const r2 = await rain.monthlyRainfall("Galle"); assert.equal(r2.cached, true); assert.equal(calls, 1);
  rain.setFetch(async () => ({ ok: true, status: 200, json: async () => ({ daily: { time: time.slice(0, 100), precipitation_sum: precip.slice(0, 100) } }) })); await RainfallCache.deleteMany({ district: "Galle" }); await assert.rejects(() => rain.monthlyRainfall("Galle"), /incomplete/); rain.setFetch(async () => ({ ok: false, status: 500 })); await assert.rejects(() => rain.monthlyRainfall("Galle"), /500/);
  const adv = rain.plantingAdvice([30, 40, 60, 90, 120, 80, 70, 60, 80, 150, 210, 160]); assert.equal(adv[0].season, "maha"); assert.equal(adv[0].plantMonth, "Oct"); assert.equal(adv[0].needsIrrigation, false); assert.equal(adv[1].season, "yala"); assert.equal(adv[1].plantMonth, "May"); const dry = rain.plantingAdvice([5, 5, 10, 20, 30, 5, 5, 5, 20, 60, 70, 10]); assert.equal(dry[0].plantMonth, "Nov"); assert.equal(dry[0].needsIrrigation, true); ok("rainfall: the average of 5 years is computed per month, cached (one call only), incomplete or failed data is rejected, and planting advice picks the first month with 100 mm+ (or the wettest month with an irrigation warning)");
  rain.setFetch((...a) => fetch(...a));

  // ================= ID VERIFICATION =================
  assert.equal((await http("POST", "/auth/verification", { token: F12.token, body: { docType: "passport", imageBase64: PNG } })).status, 400); assert.equal((await http("POST", "/auth/verification", { token: F12.token, body: { docType: "nic", imageBase64: Buffer.from("not an image").toString("base64") } })).status, 400);
  assert.equal((await http("POST", "/auth/verification", { token: F12.token, body: { docType: "nic", imageBase64: PNG } })).status, 201); assert.equal((await User.findById(F12.id)).verification.status, "pending");
  const pend = (await http("GET", "/admin/verifications", { token: ADMIN.token })).body.data.find((v) => v.userId === F12.id); assert.ok(pend && pend.photoId && pend.docType === "nic"); assert.equal((await http("GET", "/admin/verifications", { token: F.token })).status, 403);
  const docView = await http("GET", `/admin/photos/${pend.photoId}`, { token: ADMIN.token, raw: true }); assert.equal(docView.status, 200); assert.equal((await http("GET", `/photos/${pend.photoId}`, { token: F1.token, raw: true })).status, 403); ok("ID check: a farmer sends a photo of their document; only an admin can open it (another farmer gets 403); bad type / non-image refused");
  assert.equal((await http("POST", `/admin/verifications/${F12.id}`, { token: ADMIN.token, body: { decision: "maybe" } })).status, 400); assert.equal((await http("POST", `/admin/verifications/${F12.id}`, { token: ADMIN.token, body: { decision: "verified", note: "NIC matches" } })).status, 200);
  assert.equal(await Photo.countDocuments({ owner: F12.id, purpose: "verification" }), 0); assert.equal((await User.findById(F12.id)).verification.status, "verified"); assert.equal((await http("POST", "/ratings/trust", { token: B.token, body: { ids: [F12.id, F1.id] } })).body.data[F12.id].verified, true); assert.equal((await http("POST", "/ratings/trust", { token: B.token, body: { ids: [F1.id] } })).body.data[F1.id].verified, false); assert.equal((await http("POST", `/admin/verifications/${F12.id}`, { token: ADMIN.token, body: { decision: "verified" } })).status, 409); assert.equal((await http("POST", "/auth/verification", { token: F12.token, body: { docType: "nic", imageBase64: PNG } })).body.code, "already_verified"); ok("approved: the document photo is DELETED, the farmer shows as verified in trust data (others don't), it can't be decided twice");
  await http("POST", "/auth/verification", { token: B2.token, body: { docType: "business_reg", imageBase64: PNG } }); await http("POST", `/admin/verifications/${B2.id}`, { token: ADMIN.token, body: { decision: "verified" } }); assert.equal((await User.findById(B2.id)).buyerProfile.verifiedBusiness, true); await http("POST", "/auth/verification", { token: F4.token, body: { docType: "nic", imageBase64: PNG } }); await http("POST", `/admin/verifications/${F4.id}`, { token: ADMIN.token, body: { decision: "rejected", note: "Photo too blurry" } }); assert.equal((await User.findById(F4.id)).verification.status, "rejected"); assert.ok(await Reminder.findOne({ farmer: F4.id, title: /not accepted/ })); assert.equal((await http("POST", "/auth/verification", { token: F4.token, body: { docType: "nic", imageBase64: PNG } })).status, 201); ok("a verified buyer gets the business badge; a rejected farmer is told why and may try again");

  // ================= ORDER PHOTOS & DISPUTES =================
  const mk = (farmerId, crop = "Tomato", kg = 100, price = 200) => Listing.create({ farmer: farmerId, cropType: crop, quantityKg: kg, originalPricePerKg: price, currentPricePerKg: price, harvestDate: new Date(), qualityGrade: "A" });
  const L1 = await mk(F.id); const O1 = (await http("POST", "/orders", { token: B.token, body: { listingId: String(L1._id) } })).body.data.id;
  assert.equal((await http("POST", `/orders/${O1}/photos`, { token: B.token, body: { imageBase64: PNG } })).status, 409); assert.equal((await http("POST", `/orders/${O1}/dispute`, { token: B.token, body: { reason: "quality" } })).status, 409); await http("POST", `/orders/${O1}/accept`, { token: F.token }); await http("POST", `/orders/${O1}/dispatch`, { token: F.token, body: { method: "truck" } });
  const up = await http("POST", `/orders/${O1}/photos`, { token: F.token, body: { imageBase64: PNG, label: "pickup" } }); assert.equal(up.status, 201); assert.equal((await http("POST", `/orders/${O1}/photos`, { token: B.token, body: { imageBase64: PNG, label: "delivery" } })).status, 201); assert.equal((await http("POST", `/orders/${O1}/photos`, { token: F1.token, body: { imageBase64: PNG } })).status, 403); assert.equal((await http("POST", `/orders/${O1}/photos`, { token: B.token, body: { imageBase64: "AAAA" } })).status, 400);
  const plist = (await http("GET", `/orders/${O1}/photos`, { token: B.token })).body.data; assert.equal(plist.length, 2); assert.deepEqual(plist.map((p) => p.label), ["pickup", "delivery"]); assert.equal(plist.filter((p) => p.mine).length, 1); assert.equal((await http("GET", `/orders/${O1}/photos`, { token: F1.token })).status, 403); assert.equal((await http("GET", `/photos/${plist[0].id}`, { token: B.token, raw: true })).status, 200); assert.equal((await http("GET", `/photos/${plist[0].id}`, { token: F1.token, raw: true })).status, 403); assert.equal((await http("GET", `/photos/${plist[0].id}`, { token: ADMIN.token, raw: true })).status, 200); ok("delivery proof: both sides can add pickup/delivery photos and see them; strangers can't add or see; admin can");
  for (let i = 0; i < 4; i++) await http("POST", `/orders/${O1}/photos`, { token: B.token, body: { imageBase64: PNG } }); assert.equal((await http("POST", `/orders/${O1}/photos`, { token: B.token, body: { imageBase64: PNG } })).status, 409); ok("an order holds at most 6 photos");
  assert.equal((await http("POST", `/orders/${O1}/dispute`, { token: F1.token, body: { reason: "quality" } })).status, 403); assert.equal((await http("POST", `/orders/${O1}/dispute`, { token: B.token, body: { reason: "cosmic" } })).status, 400);
  const dsp = await http("POST", `/orders/${O1}/dispute`, { token: B.token, body: { reason: "quality", description: "Half the tomatoes were bruised" } }); assert.equal(dsp.status, 201); const dId = dsp.body.data.id; assert.equal((await http("POST", `/orders/${O1}/dispute`, { token: B.token, body: { reason: "quantity" } })).body.code, "already_open"); assert.ok(await Reminder.findOne({ farmer: F.id, dedupeKey: `dispute-${dId}` })); ok("a buyer reports a problem on an accepted order; the farmer is notified; a second open problem is refused");
  assert.equal((await http("POST", `/disputes/${dId}/message`, { token: F.token, body: { text: "I'll refund the bruised part" } })).status, 201); assert.equal((await http("POST", `/disputes/${dId}/message`, { token: F1.token, body: { text: "hi" } })).status, 403); assert.equal((await http("POST", `/disputes/${dId}/message`, { token: F.token, body: { text: "  " } })).status, 400); const mine = (await http("GET", "/disputes/mine", { token: F.token })).body.data.find((d) => d.id === dId); assert.equal(mine.messages.length, 2); assert.equal(mine.openedByMe, false); assert.equal((await http("GET", "/disputes/mine", { token: F1.token })).body.data.length, 0); ok("both sides can write in the case; strangers can't; each person only sees their own cases");
  const adm = (await http("GET", "/admin/disputes?status=open", { token: ADMIN.token })).body.data.find((d) => d.id === dId); assert.equal(adm.order.cropType, "Tomato"); assert.equal(adm.openedBy.fullName.includes("Green Basket"), true); assert.equal((await http("GET", "/admin/disputes", { token: F.token })).status, 403); assert.equal((await http("POST", `/admin/disputes/${dId}/message`, { token: ADMIN.token, body: { text: "Please send a photo of the bruised tomatoes." } })).status, 201);
  assert.equal((await http("POST", `/admin/disputes/${dId}/resolve`, { token: ADMIN.token, body: { outcome: "paid" } })).status, 400); assert.equal((await http("POST", `/admin/disputes/${dId}/resolve`, { token: ADMIN.token, body: { outcome: "resolved", resolution: "Farmer refunds LKR 4,000." } })).status, 200); assert.equal((await http("POST", `/admin/disputes/${dId}/resolve`, { token: ADMIN.token, body: { outcome: "dismissed" } })).status, 409); assert.equal((await http("POST", `/disputes/${dId}/message`, { token: B.token, body: { text: "thanks" } })).status, 409); assert.ok(await Reminder.findOne({ farmer: F.id, dedupeKey: `dispute-closed-${dId}` })); ok("admin reviews the case, writes to both sides, resolves it with a note; the farmer is told; a closed case takes no more messages");

  // ================= REPORTS & BLOCKS =================
  assert.equal((await http("POST", "/reports", { token: F1.token, body: { reportedId: F1.id, reason: "scam" } })).status, 400); assert.equal((await http("POST", "/reports", { token: F1.token, body: { reportedId: F2.id, reason: "boring" } })).status, 400); assert.equal((await http("POST", "/reports", { token: F1.token, body: { reportedId: F2.id, reason: "scam", context: "order", note: "Took my deposit" } })).status, 201); assert.equal((await http("POST", "/reports", { token: F1.token, body: { reportedId: F2.id, reason: "scam" } })).body.code, "duplicate"); await http("POST", "/reports", { token: F3.token, body: { reportedId: F2.id, reason: "abuse" } });
  const reps = (await http("GET", "/admin/reports", { token: ADMIN.token })).body.data.filter((r) => r.reported && String(r.reported._id) === F2.id); assert.equal(reps.length, 2); assert.equal(reps[0].reportsAgainstThisPerson, 2); assert.equal((await http("PATCH", `/admin/reports/${reps[0].id}`, { token: ADMIN.token, body: { status: "actioned" } })).status, 200); assert.equal((await http("GET", "/admin/reports", { token: F1.token })).status, 403); ok("anyone can report someone they dealt with (not themselves, once a day per reason); the admin sees how many people reported the same person");
  const L2 = await mk(F.id, "Carrot", 50, 240); assert.equal((await http("POST", "/blocks", { token: F.token, body: { userId: B2.id } })).status, 200); assert.equal((await http("POST", "/blocks", { token: F.token, body: { userId: F.id } })).status, 400); assert.equal((await http("GET", "/blocks", { token: F.token })).body.data.length, 1);
  assert.equal((await http("POST", "/orders", { token: B2.token, body: { listingId: String(L2._id) } })).body.code, "blocked"); assert.equal((await http("POST", "/blocks", { token: B2.token, body: { userId: F.id } })).status, 200); await http("DELETE", `/blocks/${B2.id}`, { token: F.token }); assert.equal((await http("POST", "/orders", { token: B2.token, body: { listingId: String(L2._id) } })).body.code, "blocked"); await http("DELETE", `/blocks/${F.id}`, { token: B2.token }); const okOrder = await http("POST", "/orders", { token: B2.token, body: { listingId: String(L2._id) } }); assert.equal(okOrder.status, 201); await http("POST", `/orders/${okOrder.body.data.id}/cancel`, { token: B2.token }); ok("blocking works in both directions: a blocked buyer can't order from that farmer (until both blocks are lifted)");
  const Lt = await http("POST", "/return-trips", { token: D.token, body: { fromHub: "Dambulla", toDistrict: "Kandy", departAt: inHours(10), availableKg: 500, pricePerKg: 12 } }); await http("POST", "/blocks", { token: D.token, body: { userId: F1.id } }); assert.equal((await http("POST", `/return-trips/${Lt.body.data.id}/book`, { token: F1.token, body: { weightKg: 20 } })).body.code, "blocked"); assert.equal((await http("POST", `/return-trips/${Lt.body.data.id}/book`, { token: F3.token, body: { weightKg: 20 } })).status, 201); await http("POST", `/return-trips/${Lt.body.data.id}/cancel`, { token: D.token }); ok("a driver can block a farmer from booking their trips");

  // ================= FEEDBACK =================
  assert.equal((await http("POST", "/feedback", { token: F1.token, body: { message: "hi" } })).status, 400); const fb = await http("POST", "/feedback", { token: F1.token, body: { kind: "bug", message: "The price board is slow on my phone", screen: "price_board", appVersion: "1.2.0", clientId: "fb-1" } }); assert.equal(fb.status, 201); assert.equal((await http("POST", "/feedback", { token: F1.token, body: { kind: "bug", message: "The price board is slow on my phone", clientId: "fb-1" } })).body.duplicate, true); assert.equal((await http("POST", "/feedback", { body: { message: "no login here" } })).status, 401);
  const fbl = (await http("GET", "/admin/feedback?status=new", { token: ADMIN.token })).body.data.filter((f) => f.screen === "price_board"); assert.equal(fbl.length, 1); assert.equal(fbl[0].kind, "bug"); assert.equal(fbl[0].user.district, "Kandy"); assert.equal((await http("PATCH", `/admin/feedback/${fbl[0].id}`, { token: ADMIN.token, body: { status: "done" } })).status, 200); assert.equal((await http("GET", "/admin/feedback", { token: F1.token })).status, 403); ok("feedback: sent once even if the phone retries (same clientId), admin sees kind, screen, app version and district, and can mark it done");
  for (let i = 0; i < 12; i++) await http("POST", "/feedback", { token: F4.token, body: { message: "spam spam " + i } }); assert.equal((await http("POST", "/feedback", { token: F4.token, body: { message: "one more please" } })).body.code, "rate_limited"); ok("feedback is limited to 10 a day per person");

  // ================= HOW TO PAY ME (payment details + QR) =================
  assert.equal((await http("GET", "/auth/me/payment", { token: F.token })).body.data.hasQr, false); assert.equal((await http("PUT", "/auth/me/payment", { token: F.token, body: { instructions: "Bank of Ceylon, Kandy branch — name Nimal Perera" } })).status, 200); assert.equal((await http("PUT", "/auth/me/payment/qr", { token: F.token, body: { imageBase64: "not-base64!!" } })).status, 400); const qr = await http("PUT", "/auth/me/payment/qr", { token: F.token, body: { imageBase64: PNG } }); assert.equal(qr.status, 200);
  const L3 = await mk(F.id, "Cabbage", 60, 130); const O3 = (await http("POST", "/orders", { token: B.token, body: { listingId: String(L3._id) } })).body.data.id; let bo = (await http("GET", "/orders/mine", { token: B.token })).body.data.find((o) => o.id === O3); assert.equal(bo.farmerPayment, undefined); await http("POST", `/orders/${O3}/accept`, { token: F.token }); assert.equal((await http("GET", `/photos/${qr.body.qrPhotoId}`, { token: B2.token, raw: true })).status, 403); await http("POST", `/orders/${O3}/dispatch`, { token: F.token, body: { method: "self" } });
  bo = (await http("GET", "/orders/mine", { token: B.token })).body.data.find((o) => o.id === O3); assert.match(bo.farmerPayment.instructions, /Bank of Ceylon/); assert.equal(bo.farmerPayment.qrPhotoId, qr.body.qrPhotoId); assert.equal((await http("GET", `/photos/${qr.body.qrPhotoId}`, { token: B.token, raw: true })).status, 200); assert.equal((await http("GET", `/photos/${qr.body.qrPhotoId}`, { token: B2.token, raw: true })).status, 403); const fo = (await http("GET", "/orders/mine", { token: F.token })).body.data.find((o) => o.id === O3); assert.equal(fo.farmerPayment, undefined);
  await http("DELETE", "/auth/me/payment/qr", { token: F.token }); assert.equal((await http("GET", "/auth/me/payment", { token: F.token })).body.data.hasQr, false); await http("POST", `/orders/${O3}/cancel`, { token: B.token, body: { qualityRejected: true, reason: "test" } }); ok("payment details: the farmer's payment note and bank-app QR photo appear to the BUYER only after dispatch; other buyers can't open the QR; the farmer's own view has no copy; the QR can be removed");

  // ================= WILDLIFE ALERTS (+ SMS monthly cap) =================
  const WildlifeSighting = M("WildlifeSighting"); const GPS = (lng, lat) => ({ type: "Point", coordinates: [lng, lat] });
  await User.updateOne({ _id: F1.id }, { $set: { "farmerProfile.gpsLocation": GPS(80.6337, 7.2906), smsAlerts: true, phone: "0714445555" } }); await User.updateOne({ _id: F2.id }, { $set: { "farmerProfile.gpsLocation": GPS(80.64, 7.3) } }); await User.updateOne({ _id: F9.id }, { $set: { "farmerProfile.gpsLocation": GPS(80.62, 7.47) } });
  assert.equal((await http("POST", "/help/wildlife", { token: F2.token, body: { species: "dragon", ...KANDY } })).status, 400); assert.equal((await http("POST", "/help/wildlife", { token: F2.token, body: { species: "elephant", latitude: 51.5, longitude: -0.1 } })).body.code, "bad_location"); assert.equal((await http("POST", "/help/wildlife", { token: F2.token, body: { species: "elephant", ...KANDY, note: "call 0771234567" } })).status, 400); assert.equal((await http("POST", "/help/wildlife", { token: B.token, body: { species: "elephant", ...KANDY } })).status, 403); assert.equal((await http("POST", "/help/wildlife", { body: { species: "elephant", ...KANDY } })).status, 401); ok("wildlife reports need a real animal and a location inside Sri Lanka; phone numbers in notes, buyers and logged-out users are refused");
  const w1 = await http("POST", "/help/wildlife", { token: F2.token, body: { species: "elephant", latitude: 7.3, longitude: 80.64, note: "Herd near the paddy", clientId: "w-1" } }); assert.equal(w1.status, 201); assert.equal(w1.body.data.district, "Kandy"); assert.ok(w1.body.data.farmersWarned >= 2); assert.equal((await http("POST", "/help/wildlife", { token: F2.token, body: { species: "elephant", latitude: 7.3, longitude: 80.64, clientId: "w-1" } })).body.duplicate, true);
  assert.ok(await Reminder.findOne({ farmer: F1.id, type: "wildlife", dedupeKey: `wild-${w1.body.data.id}` })); assert.ok(await Reminder.findOne({ farmer: F.id, type: "wildlife", dedupeKey: `wild-${w1.body.data.id}` })); assert.equal(await Reminder.countDocuments({ farmer: F2.id, dedupeKey: `wild-${w1.body.data.id}` }), 0); assert.equal(await Reminder.countDocuments({ farmer: F9.id, dedupeKey: `wild-${w1.body.data.id}` }), 0); ok(`a farmer reports elephants: ${w1.body.data.farmersWarned} farmers within 8 km are warned (not the reporter, not a farmer 20 km away); a phone retry doesn't warn twice`);
  await new Promise((r) => setTimeout(r, 400)); const f1phone = "+94714445555"; const f1sms = () => smsHits.filter((h) => h.body.to === f1phone).length; assert.equal(f1sms(), 1);
  for (const sp of ["wild_boar", "monkey", "peacock"]) await http("POST", "/help/wildlife", { token: F2.token, body: { species: sp, latitude: 7.3, longitude: 80.64 } }); await new Promise((r) => setTimeout(r, 600)); assert.equal(f1sms(), 3); assert.equal(await SmsLog.countDocuments({ user: F1.id, status: "skipped", detail: "monthly cap" }), 1); assert.ok(await Reminder.findOne({ farmer: F1.id, title: /Peacocks/ })); ok("SMS cap: an opted-in farmer gets 3 texts this month (the cap), the 4th alert still reaches their bell but no SMS is sent (logged as capped)");
  assert.equal((await http("POST", "/help/wildlife", { token: F2.token, body: { species: "other", latitude: 7.3, longitude: 80.64 } })).status, 201); assert.equal((await http("POST", "/help/wildlife", { token: F2.token, body: { species: "other", latitude: 7.3, longitude: 80.64 } })).body.code, "rate_limited"); ok("a farmer can send at most 5 wildlife reports a day");
  await WildlifeSighting.create({ reporter: F2.id, species: "monkey", location: GPS(80.6337, 7.2906), district: "Kandy", expiresAt: new Date(Date.now() - 3600000) });
  const near = (await http("GET", `/help/wildlife/nearby?latitude=${KANDY.latitude}&longitude=${KANDY.longitude}&radiusKm=10`, { token: F.token })).body.data; assert.equal(near.length, 5); assert.ok(near.every((s) => s.distanceKm <= 10 && s.minutesAgo >= 0)); assert.equal(near[near.length - 1].species, "elephant"); assert.equal((await http("GET", `/help/wildlife/nearby?latitude=9.66&longitude=80.02`, { token: F.token })).body.data.length, 0); assert.equal((await http("GET", "/help/wildlife/nearby", { token: F.token })).status, 400); ok("nearby sightings: only the 5 live ones within range (an expired one is hidden), nothing in Jaffna, location required");
  const eleId = near.find((s) => s.species === "elephant").id; let cf = await http("POST", `/help/wildlife/${eleId}/confirm`, { token: F.token, body: { kind: "seen" } }); assert.equal(cf.body.seenBy, 2); await http("POST", `/help/wildlife/${eleId}/confirm`, { token: F.token, body: { kind: "seen" } }); cf = await http("POST", `/help/wildlife/${eleId}/confirm`, { token: F1.token, body: { kind: "seen" } }); assert.equal(cf.body.seenBy, 3); cf = await http("POST", `/help/wildlife/${eleId}/confirm`, { token: F.token, body: { kind: "clear" } }); assert.equal(cf.body.seenBy, 2); assert.equal(cf.body.allClear, 1); assert.equal((await http("POST", `/help/wildlife/${eleId}/confirm`, { token: F2.token, body: { kind: "seen" } })).status, 400); ok("neighbours can confirm 'I saw them too' (counted once each) or say 'all clear'; you can't confirm your own report");

  // ================= AGRICULTURE OFFICES =================
  const off = await http("POST", "/admin/offices", { token: ADMIN.token, body: { name: "Test Agrarian Service Centre", kind: "agrarian_service_centre", district: "kandy", phone: "0812223344", hours: "Mon-Fri 8:30-4:15" } }); assert.equal(off.status, 201); assert.equal((await http("POST", "/admin/offices", { token: F.token, body: { name: "x", kind: "cooperative", district: "Kandy" } })).status, 403); assert.equal((await http("POST", "/admin/offices", { token: ADMIN.token, body: { name: "x", kind: "cooperative", district: "Atlantis" } })).status, 400);
  let ol = (await http("GET", "/help/offices?district=Kandy", { token: F.token })).body.data; assert.ok(ol.some((o) => o.name === "Test Agrarian Service Centre" && o.phone === "0812223344" && o.isSample === false)); assert.ok(ol.some((o) => o.isSample === true)); assert.equal((await http("GET", "/help/offices?district=Atlantis", { token: F.token })).status, 400); assert.ok((await http("GET", "/help/offices?kind=cooperative", { token: F.token })).body.data.every((o) => o.kind === "cooperative")); await http("PATCH", `/admin/offices/${off.body.data.id}`, { token: ADMIN.token, body: { phone: "0819999999" } }); ol = (await http("GET", "/help/offices?district=Kandy", { token: F.token })).body.data; assert.equal(ol.find((o) => o.name === "Test Agrarian Service Centre").phone, "0819999999"); await http("DELETE", `/admin/offices/${off.body.data.id}`, { token: ADMIN.token }); assert.ok(!(await http("GET", "/help/offices?district=Kandy", { token: F.token })).body.data.some((o) => o.name === "Test Agrarian Service Centre")); ok("office directory: admin adds / edits / removes real offices; farmers filter by district or kind; demo rows are flagged 'sample' so nobody mistakes them for real contacts");

  // ================= QUESTIONS FOR AN OFFICER =================
  const srch = await http("GET", `/admin/users/search?q=${encodeURIComponent("neighbour3@")}`, { token: ADMIN.token }); assert.equal(srch.status, 200); assert.equal(srch.body.data.length, 1); assert.equal(srch.body.data[0].id, F3.id); assert.equal((await http("GET", "/admin/users/search?q=a", { token: ADMIN.token })).status, 400); assert.equal((await http("GET", "/admin/users/search?q=neighbour", { token: F.token })).status, 403); assert.equal((await http("GET", "/admin/users/search?q=a.b(", { token: ADMIN.token })).status, 200); ok("admin can search people by name or email (2+ letters, special characters are safe, admin-only)");
  const setOff = await http("POST", `/admin/users/${F3.id}/officer`, { token: ADMIN.token, body: { districts: ["Kandy", "atlantis"], title: "Agriculture Instructor" } }); assert.equal(setOff.status, 200); assert.deepEqual(setOff.body.districts, ["Kandy"]); await http("POST", `/admin/users/${F9.id}/officer`, { token: ADMIN.token, body: { districts: ["Matale"], title: "Extension Officer" } }); assert.equal((await http("POST", `/admin/users/${F3.id}/officer`, { token: F.token, body: { districts: ["Kandy"] } })).status, 403); assert.equal((await http("POST", `/admin/users/${ADMIN.id}/officer`, { token: ADMIN.token, body: { districts: ["Kandy"] } })).status, 409);
  const O3t = await login(N(3)), O9t = await login(N(9)); assert.equal((await http("GET", "/help/officer/overview", { token: F.token })).status, 403);
  assert.equal((await http("POST", "/help/questions", { token: F.token, body: { text: "short" } })).status, 400); assert.equal((await http("POST", "/help/questions", { token: F.token, body: { text: "Please call me on 0771234567 about my crop" } })).body.code, "bad_text"); const q = await http("POST", "/help/questions", { token: F.token, body: { cropType: "Tomato", text: "Brown spots with yellow rings on my tomato leaves after rain — what is it?" } }); assert.equal(q.status, 201); assert.equal(q.body.data.officersInDistrict, 1);
  let ov = (await http("GET", "/help/officer/overview", { token: O3t.token })).body.data; assert.deepEqual(ov.districts, ["Kandy"]); assert.equal(ov.questions.length, 1); assert.equal(ov.questions[0].cropType, "Tomato"); assert.ok(ov.outbreaks.length >= 1 && ov.outbreaks[0].reports >= 1 && ov.outbreaks[0].district === "Kandy"); assert.equal((await http("GET", "/help/officer/overview", { token: O9t.token })).body.data.questions.length, 0); ok("an officer sees the open questions AND the disease reports of their own districts only (a Matale officer sees no Kandy questions)");
  assert.equal((await http("POST", `/help/officer/questions/${q.body.data.id}/answer`, { token: O9t.token, body: { answer: "Looks like early blight — remove affected leaves." } })).status, 403); assert.equal((await http("POST", `/help/officer/questions/${q.body.data.id}/answer`, { token: O3t.token, body: { answer: "ok" } })).status, 400); assert.equal((await http("POST", `/help/officer/questions/${q.body.data.id}/answer`, { token: O3t.token, body: { answer: "This looks like early blight. Remove affected leaves, avoid overhead watering and visit the Agrarian Service Centre for advice on approved sprays." } })).status, 200); assert.equal((await http("POST", `/help/officer/questions/${q.body.data.id}/answer`, { token: O3t.token, body: { answer: "second answer" } })).status, 409);
  const mq = (await http("GET", "/help/questions/mine", { token: F.token })).body.data[0]; assert.equal(mq.status, "answered"); assert.match(mq.answer, /early blight/); assert.equal(mq.answeredBy, "Sunil Bandara, Agriculture Instructor".replace("Sunil Bandara", (await User.findById(F3.id)).fullName)); assert.ok(await Reminder.findOne({ farmer: F.id, type: "officer_answer" })); ov = (await http("GET", "/help/officer/overview", { token: O3t.token })).body.data; assert.equal(ov.questions.length, 0); ok("only an officer of that district can answer; the farmer gets a notification and sees the answer with the officer's name and title; a question can be answered once");
  await http("POST", `/admin/users/${F3.id}/officer`, { token: ADMIN.token, body: { districts: [] } }); await http("POST", `/admin/users/${F9.id}/officer`, { token: ADMIN.token, body: { districts: [] } }); assert.equal((await User.findById(F3.id)).role, "farmer"); assert.equal((await http("POST", "/auth/register", { body: { fullName: "Sneaky", email: "sneaky@test.lk", phone: "0771111111", password: "Passw0rd!", role: "officer" } })).status, 400); ok("officers are made (and unmade) only by an admin — nobody can register themselves as an officer");

  // ================= YIELDS =================
  const Y = (t, body) => http("POST", "/records/yields", { token: t, body: { cropType: "Tomato", season: "yala", year: 2026, ...body } });
  assert.equal((await Y(F.token, { cropType: "Unobtainium", acres: 1, harvestKg: 100 })).status, 400); assert.equal((await Y(F.token, { acres: 1, harvestKg: 100, season: "monsoon" })).status, 400); assert.equal((await Y(F.token, { acres: 0, harvestKg: 100 })).status, 400); assert.equal((await Y(F.token, { acres: 1, harvestKg: 100, year: 1999 })).status, 400); assert.equal((await Y(F.token, { acres: 1, harvestKg: 90000 })).body.code, "implausible"); assert.equal((await http("POST", "/records/yields", { token: B.token, body: {} })).status, 403);
  const y1 = await Y(F1.token, { acres: 2, harvestKg: 4000, clientId: "y-1" }); assert.equal(y1.status, 201); assert.equal(y1.body.data.kgPerAcre, 2000); assert.equal((await Y(F1.token, { acres: 2, harvestKg: 4000, clientId: "y-1" })).body.duplicate, true); assert.equal(await YieldRecord.countDocuments({ farmer: F1.id }), 1); await Y(F2.token, { acres: 1, harvestKg: 3000 });
  let myY = (await http("GET", "/records/yields", { token: F.token })).body.data; let tom = myY.find((y) => y.cropType === "Tomato"); assert.equal(tom.kgPerAcre, 4500); assert.equal(tom.districtKgPerAcre, null); assert.equal(tom.neighbours, 2); await Y(F4.token, { acres: 1, harvestKg: 4000 });
  myY = (await http("GET", "/records/yields", { token: F.token })).body.data; tom = myY.find((y) => y.cropType === "Tomato"); assert.equal(tom.neighbours, 3); assert.equal(tom.districtKgPerAcre, 3000); assert.equal(myY.find((y) => y.cropType === "Carrot").districtKgPerAcre, null); ok("harvest records: sensible checks, retries not duplicated, kg/acre computed; the district average appears ONLY when 3+ other farmers have data (2 → hidden, 3 → median 3,000 kg/acre)");
  assert.equal((await http("DELETE", `/records/yields/${y1.body.data.id}`, { token: F2.token })).status, 404); assert.equal((await http("DELETE", `/records/yields/${y1.body.data.id}`, { token: F1.token })).status, 200); ok("you can delete only your own harvest records");

  // ================= SUBSIDIES =================
  const day = (n) => new Date(Date.now() + n * 86400000).toISOString().slice(0, 10);
  assert.equal((await http("POST", "/records/subsidies", { token: F1.token, body: { kind: "gold" } })).status, 400); assert.equal((await http("POST", "/records/subsidies", { token: F1.token, body: { kind: "fertilizer", receivedOn: day(-10), nextDueOn: day(-20) } })).status, 400); assert.equal((await http("POST", "/records/subsidies", { token: F1.token, body: { kind: "fertilizer", receivedOn: day(30) } })).status, 400);
  const s1 = await http("POST", "/records/subsidies", { token: F1.token, body: { kind: "fertilizer", item: "Urea", quantity: 50, unit: "kg", valueLkr: 7500, receivedOn: day(-20), nextDueOn: day(5), clientId: "s-1" } }); assert.equal(s1.status, 201); assert.equal((await http("POST", "/records/subsidies", { token: F1.token, body: { kind: "fertilizer", receivedOn: day(-20), clientId: "s-1" } })).body.duplicate, true); await http("POST", "/records/subsidies", { token: F1.token, body: { kind: "seed", item: "Paddy seed", valueLkr: 2500, receivedOn: day(-100), nextDueOn: day(-60) } });
  let sl = await http("GET", "/records/subsidies", { token: F1.token }); assert.equal(sl.body.data.length, 2); assert.equal(sl.body.totalValueLkr, 10000); assert.equal(await Reminder.countDocuments({ farmer: F1.id, type: "subsidy_due" }), 1); await http("GET", "/records/subsidies", { token: F1.token }); assert.equal(await Reminder.countDocuments({ farmer: F1.id, type: "subsidy_due" }), 1); assert.match((await Reminder.findOne({ farmer: F1.id, type: "subsidy_due" })).title, /Urea/); ok("subsidy records: totals add up; a reminder is created ONCE when the next one is due within 7 days, and none for one that was due 60 days ago");
  await http("DELETE", `/records/subsidies/${s1.body.data.id}`, { token: F1.token }); assert.equal((await http("GET", "/records/subsidies", { token: F1.token })).body.data.length, 1);

  // ================= SUPPORT PRICES =================
  assert.equal((await http("POST", "/admin/support-prices", { token: F.token, body: { cropType: "Tomato", pricePerKg: 100 } })).status, 403); assert.equal((await http("POST", "/admin/support-prices", { token: ADMIN.token, body: { cropType: "Tomato", pricePerKg: 0 } })).status, 400);
  await http("POST", "/admin/support-prices", { token: ADMIN.token, body: { cropType: "Tomato", label: "Test guaranteed", pricePerKg: 155, source: "Test notice", effectiveFrom: day(-30) } }); const sp2 = await http("POST", "/admin/support-prices", { token: ADMIN.token, body: { cropType: "Tomato", label: "Test guaranteed", pricePerKg: 160, source: "Test notice 2", effectiveFrom: day(-1) } });
  let sps = (await http("GET", "/records/support-prices", { token: F.token })).body.data.filter((p) => p.label === "Test guaranteed"); assert.equal(sps.length, 1); assert.equal(sps[0].pricePerKg, 160); await http("DELETE", `/admin/support-prices/${sp2.body.data.id}`, { token: ADMIN.token }); sps = (await http("GET", "/records/support-prices", { token: F.token })).body.data.filter((p) => p.label === "Test guaranteed"); assert.equal(sps[0].pricePerKg, 155); await M("SupportPrice").deleteMany({ label: "Test guaranteed" }); ok("support prices: the admin publishes the official guaranteed price; farmers see only the latest per crop; removing the newest reveals the previous one");

  // ================= PRICE CHECK =================
  const pcheck = (p) => http("POST", "/records/price-check", { token: F.token, body: { cropType: "Tomato", pricePerKg: p } }); const pk = (await pcheck(200)).body.data; assert.equal(pk.verdict, "ok"); assert.ok(pk.referencePerKg > 100 && pk.referencePerKg < 400); assert.equal((await pcheck(3000)).body.data.verdict, "high"); assert.equal((await pcheck(20)).body.data.verdict, "low"); assert.equal((await http("POST", "/records/price-check", { token: F.token, body: { cropType: "Unobtainium", pricePerKg: 5 } })).status, 400); assert.equal((await http("POST", "/records/price-check", { token: F.token, body: { cropType: "Beetroot", pricePerKg: 100 } })).body.data.verdict, "unknown"); ok("price check: sensible price → ok; 15× the market → high; a tenth of it → low; a crop with no recent prices → unknown");

  // ================= DAMAGE REPORTS =================
  const dmg = (t, b) => http("POST", "/records/damage", { token: t, body: { cropType: "Tomato", cause: "heavy_rain", acresAffected: 1.5, estimatedLossLkr: 240000, happenedOn: day(-3), description: "Flooding after 3 days of heavy rain", ...b } });
  assert.equal((await dmg(F.token, { cause: "aliens" })).status, 400); assert.equal((await dmg(F.token, { acresAffected: 0 })).status, 400); assert.equal((await dmg(F.token, { happenedOn: day(10) })).status, 400); assert.equal((await dmg(F.token, { photos: ["not an image"] })).status, 400); assert.equal((await dmg(B.token, {})).status, 403);
  const dr = await dmg(F.token, { photos: [PNG, PNG, PNG, PNG] }); assert.equal(dr.status, 201); const dl = (await http("GET", "/records/damage", { token: F.token })).body.data[0]; assert.equal(dl.photoIds.length, 3); assert.equal(dl.cause, "heavy_rain"); assert.equal((await http("GET", `/photos/${dl.photoIds[0]}`, { token: F.token, raw: true })).status, 200); assert.equal((await http("GET", `/photos/${dl.photoIds[0]}`, { token: F1.token, raw: true })).status, 403); ok("damage reports: cause, area and date validated; at most 3 photos kept; only the farmer (or admin) can open the photos");
  const dlink = await http("POST", "/records/report-link/damage", { token: F.token, body: { damageId: dr.body.data.id } }); assert.equal(dlink.status, 200); assert.equal((await http("POST", "/records/report-link/damage", { token: F1.token, body: { damageId: dr.body.data.id } })).status, 404); assert.equal((await http("POST", "/records/report-link/damage", { token: F.token, body: {} })).status, 404);
  const dpage = await fetch(dlink.body.url); const dhtml = await dpage.text(); assert.equal(dpage.status, 200); assert.match(dpage.headers.get("content-type"), /html/); assert.ok(dhtml.includes("Crop damage report") && dhtml.includes("Tomato") && dhtml.includes("heavy rain") && dhtml.includes("data:image/png;base64,") && dhtml.includes("not been checked by AgriLink")); assert.equal((await fetch(dlink.body.url.slice(0, -3) + "abc")).status, 410); assert.equal((await fetch(dlink.body.url.replace("/damage?", "/loan?"))).status, 403);
  const lk = await http("POST", "/records/report-link/loan", { token: F.token }); const lhtml = await (await fetch(lk.body.url)).text(); assert.ok(lhtml.includes("Farm finance summary") && lhtml.includes("Nimal Perera") && lhtml.includes("not audited") && lhtml.includes("not a guarantee") && lhtml.includes("Harvest records") && lhtml.includes("4500 kg/ac")); const expired = jwt.sign({ purpose: "loan_report", sub: F.id, farmer: F.id }, "s", { expiresIn: -10 }); const ep = await fetch(`${BASE}/records/report/loan?t=${expired}`); assert.equal(ep.status, 410); assert.ok((await ep.text()).includes("expired")); assert.equal((await fetch(`${BASE}/records/report/loan`)).status, 410); assert.equal((await http("POST", "/records/report-link/loan", { token: B.token })).status, 403); ok("printable reports: a 48-hour link opens a loan summary or a damage report (with photos) in any browser; both carry honest 'not audited / not checked' warnings; tampered, expired or missing tokens get a friendly 410 page");

  // ================= RAIN PLANNER (HTTP) =================
  await RainfallCache.deleteMany({ district: "Kandy" }); await RainfallCache.create({ district: "Kandy", monthlyMm: [90, 70, 110, 190, 160, 120, 110, 100, 170, 300, 310, 190], years: 5, fetchedAt: new Date() });
  const rp = await http("GET", "/records/rain-planner", { token: F.token }); assert.equal(rp.status, 200); assert.equal(rp.body.data.district, "Kandy"); assert.equal(rp.body.data.months.length, 12); assert.equal(rp.body.data.months[9].mm, 300); assert.equal(rp.body.data.advice.length, 2); assert.equal(rp.body.data.advice.find((a) => a.season === "yala").plantMonth, "Mar"); assert.match(rp.body.data.note, /not a forecast/); assert.equal((await http("GET", "/records/rain-planner?district=Atlantis", { token: F.token })).status, 400); assert.equal((await http("GET", "/records/rain-planner", { token: B.token })).status, 403); ok("rain planner: defaults to the farmer's own district, 12 monthly averages, Yala/Maha planting advice, an honest 'not a forecast' note; unknown district refused");
  await RainfallCache.deleteMany({ district: "Kandy" });

  // ================= ADMIN: DISTRICT IMPACT + SYSTEM HEALTH =================
  const imp = await http("GET", "/admin/impact/districts", { token: ADMIN.token }); assert.equal(imp.status, 200); const kd = imp.body.data.find((d) => d.district === "Kandy"); assert.ok(kd.farmers >= 6); assert.ok(kd.wildlifeReports7d >= 5); assert.equal(kd.openQuestions, 0); assert.ok(imp.body.total.paidOrders >= 10 && imp.body.total.soldLkr > 0 && imp.body.total.farmers >= 12); assert.equal(imp.body.data.reduce((a, d) => a + d.farmers, 0), imp.body.total.farmers); assert.equal((await http("GET", "/admin/impact/districts", { token: F.token })).status, 403); ok("district impact: real counts per district (farmers, listings, paid sales, truck bookings, wildlife reports, open questions) that add up to the totals; admin-only");
  const sys = await http("GET", "/admin/system", { token: ADMIN.token }); assert.equal(sys.status, 200); assert.equal(sys.body.data.database, "connected"); assert.ok(sys.body.data.uptimeSeconds >= 0); assert.ok(sys.body.data.errors24h >= 1); assert.ok(Array.isArray(sys.body.data.recent) && sys.body.data.recent[0].message === "boom"); assert.equal(typeof sys.body.data.needsAttention.openDisputes, "number"); assert.ok(sys.body.data.sms.sentThisMonth >= 4); assert.equal(sys.body.data.sms.gatewayConfigured, true); assert.equal(sys.body.data.pushConfigured, false); assert.ok(sys.body.data.users.admin >= 1 && sys.body.data.users.farmer >= 12); assert.equal((await http("GET", "/admin/system", { token: F.token })).status, 403); const hl = await http("GET", "/health"); assert.equal(hl.body.database, "connected"); ok("system health: database status, errors in the last 24 hours with the latest ones listed, things needing attention, SMS sent this month, push on/off, users by role — admin-only; /api/health reports the database too");

  // ================= OFFLINE RETRY SAFETY =================
  const led = { type: "expense", category: "seeds", amountLkr: 1234, clientId: "off-1" }; const l1 = await http("POST", "/ledger", { token: F1.token, body: led }); const l2 = await http("POST", "/ledger", { token: F1.token, body: led }); assert.equal(l1.status, 201); assert.equal(l2.status, 200); assert.equal(l2.body.duplicate, true); assert.equal(await LedgerEntry.countDocuments({ farmer: F1.id, clientId: "off-1" }), 1);
  const pr = { cropType: "Carrot", market: "Kandy", pricePerKg: 250, clientId: "off-p1" }; const p1 = await http("POST", "/prices/report", { token: F4.token, body: pr }); const p2 = await http("POST", "/prices/report", { token: F4.token, body: pr }); assert.equal(p1.status, 201); assert.equal(p2.body.duplicate, true); assert.equal(await MarketPrice.countDocuments({ reporter: F4.id, clientId: "off-p1" }), 1); ok("offline retries are safe: a ledger entry or price report re-sent with the same clientId is saved only once");

  // cleanup
  await User.deleteMany({ email: "admin.v5@agrilink.lk" }); await User.deleteMany({ email: /@deleted\.invalid$/ }); await User.updateMany({ _id: { $in: [F1.id, F2.id, F12.id] } }, { $set: { smsAlerts: false } }); await new Promise((r) => smsServer.close(r)); await mongoose.disconnect();
  console.log(`\nALL ${passed} UPDATE-5 END-TO-END TESTS PASSED`);
})().catch(async (e) => { console.error("\nFAILED:", e.message, (e.stack || "").split("\n").slice(1, 3).join(" | ")); try { await mongoose.disconnect(); } catch (_) {} process.exit(1); });
