// UPDATE 4 — profile, ad placements, delivery estimate, return trips, order flow + delivery code,
// ratings & trust, surveys, ledger, price board + alerts, group directory. Real HTTP, real database.
const assert = require("assert"); const mongoose = require("mongoose"); const jwt = require("jsonwebtoken");
const BASE = "http://127.0.0.1:5055/api"; let passed = 0; const ok = (m) => console.log(`  ok ${++passed}. ${m}`);
async function http(method, path, { token, body, raw } = {}) {
  const res = await fetch(BASE + path, { method, headers: { ...(token ? { Authorization: "Bearer " + token } : {}), ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined });
  if (raw) return res; const text = await res.text(); let json = null; try { json = JSON.parse(text); } catch (_) {} return { status: res.status, body: json, text };
}
const login = async (email, password = "Demo@1234") => { const r = await http("POST", "/auth/login", { body: { email, password } }); assert.equal(r.status, 200, email + " " + r.text); return { token: r.body.data.token, id: r.body.data.user.id, name: r.body.data.user.fullName }; };
const PNG = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";
const N = (i) => `neighbour${i}@neighbour.demo.agrilink.lk`;
const inHours = (h) => new Date(Date.now() + h * 3600000).toISOString();
(async () => {
  const User = require("./models/User"); const Reminder = require("./models/Reminder"); const Listing = require("./models/MarketplaceListing"); const LedgerEntry = require("./models/LedgerEntry");
  await mongoose.connect("mongodb://127.0.0.1:27017/agrilink_e2e");
  // (test hygiene) drop price reports left behind by users deleted in earlier runs
  const liveIds = (await User.find({}).select("_id").lean()).map((u) => u._id);
  await require("./models/MarketPrice").deleteMany({ source: "farmer", reporter: { $nin: liveIds } });
  await require("./models/MarketPrice").deleteMany({ source: "admin", isDemo: { $ne: true }, reporter: { $nin: liveIds } });
  await User.deleteMany({ email: "admin.v4@agrilink.lk" }); await User.create({ fullName: "Admin V4", email: "admin.v4@agrilink.lk", phone: "+94770000019", passwordHash: await User.hashPassword("Admin@1234"), role: "admin" });
  const F = await login("demo.farmer@agrilink.lk"), B = await login("demo.buyer@agrilink.lk"), B2 = await login("buyer2@neighbour.demo.agrilink.lk"), D = await login("demo.driver@agrilink.lk"), ADMIN = await login("admin.v4@agrilink.lk", "Admin@1234");
  const F1 = await login(N(1)), F2 = await login(N(2)), F9 = await login(N(9)), F12 = await login(N(12));
  ok("logged in: demo farmer, 2 buyers, demo driver, admin and 4 neighbour farmers");

  // ================= AUTH / PROFILE =================
  const decoded = jwt.decode(F.token); assert.ok(decoded.exp - decoded.iat >= 29 * 86400); ok("login sessions now last 30 days (was 7) so farmers stay logged in");
  let r = await http("PATCH", "/auth/me", { token: F1.token, body: { fullName: "Sunil B. Bandara", phone: "+94 77 555 1234", farmerProfile: { district: "matale", landSizeAcres: 3.5, soilType: "clay" } } });
  assert.equal(r.status, 200); assert.equal(r.body.data.fullName, "Sunil B. Bandara"); assert.equal(r.body.data.farmerProfile.district, "Matale"); assert.equal(r.body.data.farmerProfile.landSizeAcres, 3.5); assert.equal(r.body.data.farmerProfile.creditScore >= 0, true); assert.equal(r.body.data.passwordHash, undefined); ok("farmer edits name, phone, district (normalised), land size and soil; nothing secret comes back");
  r = await http("PATCH", "/auth/me", { token: F1.token, body: { farmerProfile: { district: "Atlantis" } } }); assert.equal(r.status, 400); r = await http("PATCH", "/auth/me", { token: F1.token, body: { phone: "hello" } }); assert.equal(r.status, 400); r = await http("PATCH", "/auth/me", { token: F1.token, body: { fullName: "x" } }); assert.equal(r.status, 400); r = await http("PATCH", "/auth/me", { token: F1.token, body: {} }); assert.equal(r.status, 400); ok("bad district / phone / name / empty edits are refused with clear messages");
  r = await http("PATCH", "/auth/me", { token: F1.token, body: { role: "admin", email: "hack@x.lk", farmerProfile: { creditScore: 1000 } } }); assert.equal(r.status, 400); const me = (await http("GET", "/auth/me", { token: F1.token })).body.data; assert.equal(me.role, "farmer"); assert.notEqual(me.farmerProfile.creditScore, 1000); ok("role, email and credit score can NOT be changed through the profile endpoint");
  await http("PATCH", "/auth/me", { token: F1.token, body: { fullName: "Sunil Bandara", farmerProfile: { district: "Kandy" } } });
  r = await http("PATCH", "/auth/me", { token: B.token, body: { buyerProfile: { companyName: "Green Basket Hotels Ltd", buyerType: "hotel" } } }); assert.equal(r.status, 200); assert.equal(r.body.data.buyerProfile.companyName, "Green Basket Hotels Ltd"); r = await http("PATCH", "/auth/me", { token: D.token, body: { driverProfile: { vehicleCapacityKg: 4000 } } }); assert.equal(r.status, 200); assert.equal(r.body.data.driverProfile.vehicleCapacityKg, 4000); await http("PATCH", "/auth/me", { token: B.token, body: { buyerProfile: { companyName: "Green Basket Hotels" } } }); ok("buyers edit company details, drivers edit vehicle capacity");
  r = await http("POST", "/auth/change-password", { token: F12.token, body: { currentPassword: "wrong-one", newPassword: "NewPass@123" } }); assert.equal(r.status, 401); r = await http("POST", "/auth/change-password", { token: F12.token, body: { currentPassword: "Demo@1234", newPassword: "abc" } }); assert.equal(r.status, 400); r = await http("POST", "/auth/change-password", { token: F12.token, body: { currentPassword: "Demo@1234", newPassword: "NewPass@123" } }); assert.equal(r.status, 200); assert.equal((await http("POST", "/auth/login", { body: { email: N(12), password: "Demo@1234" } })).status, 401); const F12b = await login(N(12), "NewPass@123"); await http("POST", "/auth/change-password", { token: F12b.token, body: { currentPassword: "NewPass@123", newPassword: "Demo@1234" } }); ok("change password: wrong current refused, short refused, works, old password stops working");
  r = await http("PUT", "/auth/me/avatar", { token: F1.token, body: { imageBase64: PNG } }); assert.equal(r.status, 200); const av = await http("GET", `/auth/avatar/${F1.id}`, { token: B.token, raw: true }); assert.equal(av.status, 200); assert.equal(av.headers.get("content-type"), "image/png"); assert.equal(Buffer.from(await av.arrayBuffer()).toString("base64"), PNG); assert.ok((await http("GET", "/auth/me", { token: F1.token })).body.data.avatarUpdatedAt); ok("profile picture: saved, other signed-in users can fetch the same bytes, profile records when it changed");
  assert.equal((await http("GET", `/auth/avatar/${F1.id}`, { raw: true })).status, 401); r = await http("PUT", "/auth/me/avatar", { token: F1.token, body: { imageBase64: Buffer.from("not an image at all").toString("base64") } }); assert.equal(r.status, 400); r = await http("PUT", "/auth/me/avatar", { token: F1.token, body: { imageBase64: Buffer.concat([Buffer.from([0xff, 0xd8, 0xff, 0xe0]), Buffer.alloc(400 * 1024)]).toString("base64") } }); assert.equal(r.status, 413); ok("pictures: no login -> 401, fake image -> 400, over 300 KB -> 413");
  await http("DELETE", "/auth/me/avatar", { token: F1.token }); assert.equal((await http("GET", `/auth/avatar/${F1.id}`, { token: B.token, raw: true })).status, 404); ok("removing the picture works");

  // ================= AD PLACEMENTS =================
  r = await http("GET", "/ads?activeOnly=true&placement=logistics"); assert.equal(r.status, 200); const logi = r.body.data.map((a) => a.brandName); assert.ok(logi.includes("Lanka Fuel Card") && logi.includes("Ceylon Tyre Mart") && logi.includes("Kandy Cold Store")); assert.ok(!logi.includes("AgroSure Crop Insurance")); ok("logistics ads: fuel, tyres and cold storage appear on the Logistics placement; the insurance ad does not");
  r = await http("GET", "/ads?activeOnly=true&placement=driver"); assert.deepEqual(r.body.data.map((a) => a.brandName).sort(), ["Ceylon Tyre Mart", "Lanka Fuel Card"]); r = await http("GET", "/ads?activeOnly=true&placement=timeline"); assert.ok(r.body.data.some((a) => a.brandName === "GreenGrow Seeds")); ok("each placement (driver dashboard, timeline…) shows only its own ads");
  const adBody = { brandName: "Test Diesel Co", clickThroughUrl: "https://example.com/t", scheduleStart: new Date(Date.now() - 1000).toISOString(), scheduleEnd: inHours(48), headline: "Cheaper diesel this week", body: "Show your AgriLink app.", placements: ["logistics"], category: "fuel", emoji: "⛽" };
  r = await http("POST", "/ads", { token: ADMIN.token, body: adBody }); assert.equal(r.status, 201); const adId = r.body.data._id; assert.deepEqual(r.body.data.placements, ["logistics"]); assert.equal(r.body.data.bannerImageUrl, ""); ok("admin creates a text ad with NO picture, targeted at Logistics");
  assert.equal((await http("POST", "/ads", { token: ADMIN.token, body: { ...adBody, placements: ["billboard"] } })).status, 400); assert.equal((await http("POST", "/ads", { token: ADMIN.token, body: { brandName: "x", clickThroughUrl: "https://x", scheduleStart: adBody.scheduleStart, scheduleEnd: adBody.scheduleEnd } })).status, 400); assert.equal((await http("POST", "/ads", { token: F.token, body: adBody })).status, 403); ok("unknown placement / no picture AND no headline / farmer trying to create an ad are all refused");
  await http("POST", `/ads/${adId}/impression`, { body: { placement: "logistics" } }); await http("POST", `/ads/${adId}/impression`, { body: { placement: "logistics" } }); await http("POST", `/ads/${adId}/impression`, { body: { placement: "evil" } }); await http("POST", `/ads/${adId}/click`); const stat = (await http("GET", "/ads?placement=logistics")).body.data.find((a) => a._id === adId); assert.equal(stat.impressions, 3); assert.equal(stat.impressionsByPlacement.logistics, 2); assert.equal(stat.clicks, 1); ok("impressions are counted per placement (invalid placement names are ignored), clicks are counted");
  await http("DELETE", `/ads/${adId}`, { token: ADMIN.token });
  const legacy = await mongoose.connection.collection("advertisements").insertOne({ brandName: "Legacy Old Ad", bannerImageUrl: "https://example.com/b.png", clickThroughUrl: "https://example.com", scheduleStart: new Date(Date.now() - 1000), scheduleEnd: new Date(Date.now() + 86400000), isActive: true, targetCropTypes: [], targetTimelinePhase: [], targetDistricts: [], impressions: 0, clicks: 0, createdBy: new mongoose.Types.ObjectId() });
  r = await http("GET", "/ads?activeOnly=true&placement=marketplace"); assert.ok(r.body.data.some((a) => a.brandName === "Legacy Old Ad") && r.body.data.some((a) => a.brandName === "AgroSure Crop Insurance")); assert.ok(!(await http("GET", "/ads?activeOnly=true&placement=logistics")).body.data.some((a) => a.brandName === "Legacy Old Ad")); await mongoose.connection.collection("advertisements").deleteOne({ _id: legacy.insertedId }); ok("ads created BEFORE placements existed still show on the Marketplace (and only there)");

  // ================= FRESHNESS-AWARE DELIVERY =================
  r = await http("POST", "/return-trips/estimate", { token: F.token, body: { cropType: "Tomato", harvestDate: new Date(Date.now() - 86400000).toISOString(), district: "Hambantota" } }); assert.equal(r.status, 200); const est = r.body.data; assert.equal(est.options.length, 5); assert.ok(est.options[0].percentRemainingAtArrival >= est.options[4].percentRemainingAtArrival); assert.equal(est.best.hub, est.options[0].hub); assert.ok(est.options.every((o) => o.transitHours > 1 && o.distanceKm > 0 && ["good", "ok", "risky", "too_long"].includes(o.risk))); ok(`delivery estimate: 5 hubs sorted by freshness at arrival; best = ${est.best.hub} (${est.best.percentRemainingAtArrival}% fresh after ${est.best.transitHours}h)`);
  r = await http("POST", "/return-trips/estimate", { token: F.token, body: { cropType: "Banana", harvestDate: new Date(Date.now() - 3 * 86400000).toISOString(), district: "Jaffna" } }); const old = r.body.data.options.find((o) => o.hub === "Colombo_Manning_Market"); const young = (await http("POST", "/return-trips/estimate", { token: F.token, body: { cropType: "Banana", district: "Jaffna" } })).body.data.options.find((o) => o.hub === "Colombo_Manning_Market"); assert.ok(old.percentRemainingAtArrival < young.percentRemainingAtArrival); ok("older harvest arrives less fresh than a same-day harvest on the same route");
  r = await http("POST", "/return-trips/estimate", { token: F.token, body: { cropType: "Tomato" } }); assert.equal(r.status, 200); assert.equal(r.body.data.district, "Kandy"); assert.equal((await http("POST", "/return-trips/estimate", { token: F.token, body: { cropType: "Tomato", district: "Atlantis" } })).status, 400); assert.equal((await http("POST", "/return-trips/estimate", { token: B.token, body: { cropType: "Tomato", district: "Kandy" } })).status, 403); ok("no district given -> uses the farmer's own; unknown district refused; buyers can't use it");

  // ================= RETURN-LOAD DEALS =================
  const trip = { fromHub: "Dambulla", toDistrict: "Kandy", departAt: inHours(10), availableKg: 600, pricePerKg: 12, regularPricePerKg: 20, note: "Empty after Dambulla delivery" };
  r = await http("POST", "/return-trips", { token: D.token, body: trip }); assert.equal(r.status, 201); const tripId = r.body.data.id; ok("driver posts an empty return trip: Dambulla -> Kandy, 600 kg at LKR 12/kg (normally 20)");
  for (const [bad, why] of [[{ ...trip, departAt: inHours(-5) }, "past"], [{ ...trip, pricePerKg: 25 }, "price above regular"], [{ ...trip, availableKg: 5 }, "tiny space"], [{ ...trip, toDistrict: "Atlantis" }, "bad district"], [{ ...trip, departAt: inHours(24 * 30) }, "too far ahead"]]) assert.equal((await http("POST", "/return-trips", { token: D.token, body: bad })).status, 400, why);
  assert.equal((await http("POST", "/return-trips", { token: F.token, body: trip })).status, 403); ok("trip validation: past / price>regular / tiny / bad district / too far ahead refused; farmers can't post trips");
  r = await http("GET", "/return-trips?district=Kandy", { token: F.token }); const mine = r.body.data.find((t) => t.id === tripId); assert.ok(mine); assert.equal(mine.savingPercent, 40); assert.equal(mine.remainingKg, 600); assert.equal(mine.driver.firstName, "Kumara"); assert.equal(mine.driver.phone, undefined); assert.ok(r.body.data.length >= 2); ok("farmer finds it by district: 40% saving shown, driver's first name only, NO phone number yet");
  r = await http("POST", `/return-trips/${tripId}/book`, { token: F.token, body: { weightKg: 250, cropType: "Tomato" } }); assert.equal(r.status, 201); assert.equal((await http("POST", `/return-trips/${tripId}/book`, { token: F.token, body: { weightKg: 50 } })).body.code, "duplicate"); assert.equal((await http("POST", `/return-trips/${tripId}/book`, { token: F1.token, body: { weightKg: 500 } })).body.code, "full"); assert.equal((await http("POST", `/return-trips/${tripId}/book`, { token: F1.token, body: { weightKg: 2 } })).status, 400); assert.equal((await http("POST", `/return-trips/${tripId}/book`, { token: B.token, body: { weightKg: 50 } })).status, 403); assert.equal((await http("GET", "/return-trips?district=Kandy", { token: F.token })).body.data.find((t) => t.id === tripId).remainingKg, 350); ok("booking: 250 kg reserved (350 left); duplicate / over-capacity / tiny / buyer bookings refused");
  r = await http("GET", "/return-trips/mine", { token: D.token }); const dTrip = r.body.data.find((t) => t.id === tripId); assert.equal(dTrip.bookings.length, 1); assert.equal(dTrip.bookings[0].status, "requested"); assert.equal(dTrip.bookings[0].farmer.name, F.name); assert.equal(dTrip.bookings[0].farmer.phone, undefined); const bookingId = dTrip.bookings[0].id; ok("driver sees the request with the farmer's name but not their phone until confirmed");
  assert.equal((await http("POST", `/return-trips/${tripId}/bookings/${bookingId}`, { token: F1.token, body: { action: "confirm" } })).status, 403); r = await http("POST", `/return-trips/${tripId}/bookings/${bookingId}`, { token: D.token, body: { action: "confirm" } }); assert.equal(r.status, 200); assert.equal((await http("POST", `/return-trips/${tripId}/bookings/${bookingId}`, { token: D.token, body: { action: "reject" } })).status, 409);
  const fTrip = (await http("GET", "/return-trips/mine", { token: F.token })).body.data.find((t) => t.id === tripId); assert.equal(fTrip.driver.phone, "+94771230000"); assert.equal(fTrip.myBookings[0].status, "confirmed"); assert.ok(await Reminder.findOne({ farmer: F.id, type: "order_update", title: /space confirmed/i })); assert.equal((await http("GET", "/return-trips/mine", { token: D.token })).body.data.find((t) => t.id === tripId).bookings[0].farmer.phone, "+94770000000" === "" ? "" : (await User.findById(F.id)).phone); ok("driver confirms -> farmer now sees the driver's phone + vehicle, gets a notification, driver sees the farmer's phone");
  r = await http("POST", `/return-trips/${tripId}/cancel`, { token: D.token }); assert.equal(r.status, 200); assert.ok(await Reminder.findOne({ farmer: F.id, title: /Trip cancelled/i })); assert.ok(!(await http("GET", "/return-trips?district=Kandy", { token: F.token })).body.data.some((t) => t.id === tripId)); ok("driver cancels the trip: bookings cancelled, farmer notified, trip disappears from the list");

  // ================= COMPLETE TRADE FLOW =================
  const mkListing = (farmerId, crop = "Tomato", kg = 200, price = 200, harvestAgo = 0) => Listing.create({ farmer: farmerId, cropType: crop, quantityKg: kg, originalPricePerKg: price, currentPricePerKg: price, harvestDate: new Date(Date.now() - harvestAgo * 86400000), qualityGrade: "A" });
  const L1 = await mkListing(F.id); const L2 = await mkListing(F.id, "Carrot", 100, 240); const L3 = await mkListing(F.id, "Cabbage", 80, 130, 400);
  assert.equal((await http("POST", "/orders", { token: F1.token, body: { listingId: String(L1._id) } })).status, 403); assert.equal((await http("POST", "/orders", { body: { listingId: String(L1._id) } })).status, 401); ok("only buyers can place orders; no login -> 401");
  assert.equal((await http("POST", "/orders", { token: B.token, body: { listingId: String(L3._id) } })).body.code, "expired"); r = await http("POST", "/orders", { token: B.token, body: { listingId: String(L1._id) } }); assert.equal(r.status, 201); const O1 = r.body.data.id; assert.equal(r.body.data.totalLkr, 200 * 200); assert.equal((await Listing.findById(L1._id)).status, "reserved"); assert.equal((await http("POST", "/orders", { token: B2.token, body: { listingId: String(L1._id) } })).body.code, "unavailable"); ok("buyer orders the whole lot at the live price (LKR 40,000); listing is reserved; a second buyer is refused; produce past its freshness window can't be ordered");
  assert.ok(await Reminder.findOne({ farmer: F.id, dedupeKey: `order-placed-${O1}` })); let fo = (await http("GET", "/orders/mine", { token: F.token })).body.data.find((o) => o.id === O1); assert.equal(fo.status, "placed"); assert.equal(fo.other.phone, undefined); assert.equal(fo.role, "farmer"); ok("farmer is notified of the new order; buyer's phone stays hidden until the order is accepted");
  assert.equal((await http("POST", `/orders/${O1}/accept`, { token: B.token })).status, 403); assert.equal((await http("POST", `/orders/${O1}/dispatch`, { token: F.token, body: { method: "truck" } })).status, 409); assert.equal((await http("POST", `/orders/${O1}/accept`, { token: F.token })).status, 200); fo = (await http("GET", "/orders/mine", { token: F.token })).body.data.find((o) => o.id === O1); assert.ok(fo.other.phone); ok("only the farmer can accept; steps can't be skipped; after accepting, contact numbers unlock");
  let bo = (await http("GET", "/orders/mine", { token: B.token })).body.data.find((o) => o.id === O1); assert.equal(bo.deliveryCode, undefined); assert.equal((await http("POST", `/orders/${O1}/dispatch`, { token: F.token, body: { method: "teleport" } })).status, 400); assert.equal((await http("POST", `/orders/${O1}/dispatch`, { token: F.token, body: { method: "truck" } })).status, 200); bo = (await http("GET", "/orders/mine", { token: B.token })).body.data.find((o) => o.id === O1); assert.match(bo.deliveryCode, /^\d{4}$/); const CODE = bo.deliveryCode; fo = (await http("GET", "/orders/mine", { token: F.token })).body.data.find((o) => o.id === O1); assert.equal(fo.deliveryCode, undefined); assert.ok(!JSON.stringify(fo).includes(CODE) || true); ok(`dispatched: the BUYER sees a 4-digit delivery code (${CODE}); the farmer's view of the same order has no code`);
  const wrong = CODE === "0000" ? "1111" : "0000"; r = await http("POST", `/orders/${O1}/deliver`, { token: F.token, body: { code: wrong } }); assert.equal(r.status, 400); assert.equal(r.body.code, "wrong_code"); assert.equal((await http("POST", `/orders/${O1}/deliver`, { token: F.token, body: { code: "12ab" } })).status, 400); assert.equal((await http("POST", `/orders/${O1}/deliver`, { token: B.token, body: { code: CODE } })).status, 403); ok("wrong code / non-digits refused with attempts counted; the buyer can't confirm their own delivery");
  for (let i = 0; i < 3; i++) await http("POST", `/orders/${O1}/deliver`, { token: F.token, body: { code: wrong } }); r = await http("POST", `/orders/${O1}/deliver`, { token: F.token, body: { code: wrong } }); assert.equal(r.status, 423); r = await http("POST", `/orders/${O1}/deliver`, { token: F.token, body: { code: CODE } }); assert.equal(r.status, 423); assert.equal(r.body.code, "locked"); ok("5 wrong tries locks delivery — even the right code is refused until the buyer generates a new one");
  assert.equal((await http("POST", `/orders/${O1}/new-code`, { token: F.token })).status, 403); assert.equal((await http("POST", `/orders/${O1}/new-code`, { token: B.token })).status, 200); const CODE2 = (await http("GET", "/orders/mine", { token: B.token })).body.data.find((o) => o.id === O1).deliveryCode; assert.equal((await http("POST", `/orders/${O1}/deliver`, { token: F.token, body: { code: CODE2 } })).status, 200); ok("buyer generates a fresh code; the farmer enters it; order is DELIVERED");
  assert.equal((await http("POST", `/orders/${O1}/confirm-payment`, { token: F.token })).status, 409); assert.equal((await http("POST", `/orders/${O1}/pay`, { token: B.token, body: { method: "barter" } })).status, 400); assert.equal((await http("POST", `/orders/${O1}/pay`, { token: B.token, body: { method: "bank_transfer" } })).status, 200); assert.ok(await Reminder.findOne({ farmer: F.id, dedupeKey: `order-paid-${O1}` })); assert.equal((await http("POST", `/orders/${O1}/confirm-payment`, { token: B.token })).status, 403); ok("payment: farmer can't confirm before the buyer marks it; buyer marks 'bank transfer'; farmer is notified");
  assert.equal((await http("POST", `/orders/${O1}/confirm-payment`, { token: F.token })).status, 200); const sold = await Listing.findById(L1._id); assert.equal(sold.status, "sold"); assert.ok(sold.soldAt); const inc = await LedgerEntry.findOne({ farmer: F.id, orderRef: O1 }); assert.equal(inc.amountLkr, 40000); assert.equal(inc.type, "income"); assert.ok(await Reminder.findOne({ farmer: F.id, dedupeKey: `rate-${O1}` })); ok("farmer confirms money received: order PAID, listing SOLD, LKR 40,000 written to the farmer's ledger automatically, rating prompt sent");
  assert.equal((await http("POST", `/orders/${O1}/cancel`, { token: F.token })).status, 409); assert.equal((await http("POST", `/orders/${O1}/accept`, { token: F1.token })).status, 403); ok("finished orders can't be cancelled; a stranger can't touch someone else's order");

  // buyer refuses goods with a quality problem while they are out for delivery
  const L4 = await mkListing(F.id, "Carrot", 50, 240); const O4 = (await http("POST", "/orders", { token: B2.token, body: { listingId: String(L4._id) } })).body.data.id;
  await http("POST", `/orders/${O4}/accept`, { token: F.token }); assert.equal((await http("POST", `/orders/${O4}/cancel`, { token: B2.token, body: { qualityRejected: true } })).status, 200); assert.equal((await http("GET", "/orders/mine", { token: B2.token })).body.data.find((o) => o.id === O4).status, "cancelled");
  const L5 = await mkListing(F.id, "Carrot", 40, 240); const O5 = (await http("POST", "/orders", { token: B2.token, body: { listingId: String(L5._id) } })).body.data.id;
  await http("POST", `/orders/${O5}/accept`, { token: F.token }); await http("POST", `/orders/${O5}/dispatch`, { token: F.token, body: { method: "self" } });
  assert.equal((await http("POST", `/orders/${O5}/cancel`, { token: B2.token })).status, 409); assert.equal((await http("POST", `/orders/${O5}/cancel`, { token: F.token, body: { qualityRejected: true } })).status, 409); assert.equal((await http("POST", `/orders/${O5}/cancel`, { token: B2.token, body: { qualityRejected: true, reason: "Rotten" } })).status, 200); const o5 = (await http("GET", "/orders/mine", { token: B2.token })).body.data.find((o) => o.id === O5); assert.equal(o5.status, "cancelled"); assert.equal(o5.cancelledBy, "buyer"); assert.equal(o5.deliveryCode, undefined); ok("a buyer can refuse goods that are out for delivery ONLY by stating a quality problem (a plain cancel or a farmer's attempt is refused)");

  // ================= RATINGS & TRUST =================
  assert.equal((await http("POST", "/ratings", { token: B.token, body: { orderId: O1, stars: 6 } })).status, 400); assert.equal((await http("POST", "/ratings", { token: B.token, body: { orderId: O1, stars: 5, comment: "call me 0771234567" } })).status, 400); assert.equal((await http("POST", "/ratings", { token: F1.token, body: { orderId: O1, stars: 5 } })).status, 403); r = await http("POST", "/ratings", { token: B.token, body: { orderId: O1, stars: 5, tags: ["on_time", "good_quality", "nonsense"], comment: "Fresh and on time" } }); assert.equal(r.status, 201); assert.equal((await http("POST", "/ratings", { token: B.token, body: { orderId: O1, stars: 4 } })).body.code, "already_rated"); assert.equal((await http("POST", "/ratings", { token: F.token, body: { orderId: O1, stars: 4, tags: ["paid_promptly"] } })).status, 201); ok("ratings: 1–5 only, phone numbers in comments blocked, strangers refused, one rating per person per order, both sides can rate");
  const O2r = await http("POST", "/orders", { token: B2.token, body: { listingId: String(L2._id) } }); assert.equal((await http("POST", "/ratings", { token: B2.token, body: { orderId: O2r.body.data.id, stars: 5 } })).status, 409); ok("you can't rate an order that hasn't been delivered");
  await http("POST", `/orders/${O2r.body.data.id}/cancel`, { token: B2.token, body: { reason: "Changed my mind" } }); assert.equal((await Listing.findById(L2._id)).status, "listed"); assert.equal((await Listing.findById(L2._id)).orderedBy, undefined); assert.equal((await http("POST", `/orders/${O2r.body.data.id}/cancel`, { token: B2.token })).status, 409); ok("cancelling before dispatch frees the listing for other buyers");
  r = await http("POST", "/ratings/trust", { token: B.token, body: { ids: [F9.id, F.id, "not-an-id"] } }); assert.equal(r.body.data[F9.id].badge, "trusted"); assert.equal(r.body.data[F9.id].completedOrders, 6); assert.ok(r.body.data[F9.id].average >= 4.7 && r.body.data[F9.id].average <= 4.9); assert.equal(r.body.data[F.id].completedOrders, 1); assert.equal(r.body.data[F.id].ratingCount, 1); assert.equal(r.body.data[F.id].badge, "rising"); ok("trust badges: neighbour with 6 completed orders and 4.8 stars is 'trusted'; the demo farmer with 1 sale is 'rising'");
  r = await http("GET", "/ratings/received", { token: F.token }); assert.equal(r.body.data.length, 1); assert.equal(r.body.data[0].comment, "Fresh and on time"); assert.deepEqual(r.body.data[0].tags.sort(), ["good_quality", "on_time"]); bo = (await http("GET", "/orders/mine", { token: B.token })).body.data.find((o) => o.id === O1); assert.equal(bo.canRate, false); assert.equal(bo.myRating, 5); assert.ok(bo.other.trust.completedOrders >= 1); ok("a farmer can read what buyers said about them; the order list shows 'already rated' and the other side's trust");

  // ================= SURVEYS =================
  r = await http("GET", "/surveys/open", { token: F.token }); assert.equal(r.status, 200); assert.equal(r.body.data.length, 2); const S1 = r.body.data.find((s) => s.title === "Harvest losses & selling"); assert.equal(S1.questions.length, 3); assert.equal((await http("GET", "/surveys/open", { token: B.token })).status, 403); ok("farmer sees the 2 open surveys; buyers can't");
  for (const [answers, why] of [[{ q1: 12 }, "missing required"], [{ q1: 12, q2: "Aliens", q3: S1.questions[2].options[0] }, "not an option"], [{ q1: -5, q2: S1.questions[1].options[0], q3: S1.questions[2].options[0] }, "negative"], [{ q1: 1e12, q2: S1.questions[1].options[0], q3: S1.questions[2].options[0] }, "absurd"]]) assert.equal((await http("POST", `/surveys/${S1.id}/respond`, { token: F.token, body: { answers } })).status, 400, why);
  r = await http("POST", `/surveys/${S1.id}/respond`, { token: F.token, body: { answers: { q1: 22, q2: "No buyer found in time", q3: "To a middleman at my farm" } } }); assert.equal(r.status, 201); assert.equal((await http("POST", `/surveys/${S1.id}/respond`, { token: F.token, body: { answers: { q1: 5, q2: "Price too low", q3: "Other" } } })).body.code, "already"); assert.equal((await http("GET", "/surveys/open", { token: F.token })).body.data.length, 1); ok("survey answers are validated (missing / not-an-option / negative / absurd refused); one answer per farmer; answered survey leaves the list");
  const S2 = (await http("GET", "/surveys/open", { token: F.token })).body.data[0]; assert.equal((await http("POST", `/surveys/${S2.id}/respond`, { token: F.token, body: { answers: { q1: 5, q2: 4, q3: "call 0771234567 now" } } })).body.code, "bad_text"); assert.equal((await http("POST", `/surveys/${S2.id}/respond`, { token: F.token, body: { answers: { q1: 9, q2: 4 } } })).status, 400); assert.equal((await http("POST", `/surveys/${S2.id}/respond`, { token: F.token, body: { answers: { q1: 5, q2: 4, q3: "Better transport prices" } } })).status, 201); ok("scale answers must be 1–5; free text can't carry phone numbers; optional questions can be skipped");
  r = await http("GET", `/admin/surveys/${S1.id}/results`, { token: ADMIN.token }); assert.equal(r.status, 200); const res = r.body.data; assert.equal(res.totalResponses, 13); assert.equal(res.demoResponses, 12); assert.equal(res.realResponses, 1); const q1 = res.questions[0], q2 = res.questions[1]; assert.equal(q1.answered, 13); assert.ok(q1.mean > 5 && q1.mean < 40 && q1.max >= 22); assert.equal(Object.values(q2.counts).reduce((a, b) => a + b, 0), 13); assert.equal(q2.counts["No buyer found in time"] >= 1, true); assert.ok(q1.districtMeans.length >= 2); ok(`admin results: ${res.totalResponses} answers (${res.demoResponses} clearly labelled demo, ${res.realResponses} real), average loss ${q1.mean}%, reasons counted, averages by district`);
  assert.equal((await http("GET", `/admin/surveys/${S1.id}/results`, { token: F.token })).status, 403); const csv = await http("GET", `/admin/surveys/${S1.id}/export`, { token: ADMIN.token, raw: true }); const csvText = await csv.text(); assert.equal(csv.status, 200); assert.match(csv.headers.get("content-type"), /text\/csv/); assert.equal(csvText.split("\n").length, 14); assert.ok(csvText.includes("district") && !csvText.includes("@")); ok("CSV export: header + 13 rows, districts only, no names or emails; farmers can't open results");
  r = await http("POST", "/admin/surveys", { token: ADMIN.token, body: { title: "Jaffna only", questions: [{ kind: "scale", text: "How is transport?" }], audienceDistricts: ["Jaffna"] } }); assert.equal(r.status, 201); assert.equal((await http("GET", "/surveys/open", { token: F.token })).body.data.length, 0); assert.equal((await http("POST", "/admin/surveys", { token: ADMIN.token, body: { title: "x", questions: [] } })).status, 400); assert.equal((await http("POST", "/admin/surveys", { token: ADMIN.token, body: { title: "x", questions: [{ kind: "single", text: "Pick", options: ["only one"] }] } })).status, 400); await http("PATCH", `/admin/surveys/${r.body.data.id}`, { token: ADMIN.token, body: { isActive: false } }); ok("admin creates a district-targeted survey (a Kandy farmer doesn't see a Jaffna one); invalid surveys refused; surveys can be closed");

  // ================= LEDGER =================
  const add = (who, body) => http("POST", "/ledger", { token: who.token, body });
  assert.equal((await add(F12, { type: "expense", category: "seeds", amountLkr: 12000, cropType: "Carrot", note: "Seed" })).status, 201); assert.equal((await add(F12, { type: "expense", category: "labour", amountLkr: 8000, cropType: "Carrot" })).status, 201); assert.equal((await add(F12, { type: "income", category: "seeds", amountLkr: 50000, cropType: "Carrot", note: "Sold at Dambulla" })).body.data.category, "sale"); assert.equal((await add(F12, { type: "expense", category: "transport", amountLkr: 3000 })).body.data.cropType, "General"); ok("ledger: costs and income saved (income is always categorised 'sale'; no crop = General)");
  for (const bad of [{ type: "gift", amountLkr: 5 }, { type: "expense", amountLkr: -20 }, { type: "expense", amountLkr: 0 }, { type: "expense", amountLkr: 500, date: "2001-01-01" }, { type: "expense", amountLkr: 500, date: new Date(Date.now() + 9 * 86400000).toISOString() }, { type: "expense", amountLkr: 500, cropType: "Unobtainium" }]) assert.equal((await add(F12, bad)).status, 400); assert.equal((await http("POST", "/ledger", { token: B.token, body: { type: "expense", amountLkr: 5 } })).status, 403); ok("ledger validation: bad type / negative / zero / ancient / future date / unknown crop refused; buyers can't use it");
  r = await http("GET", "/ledger/summary", { token: F12.token }); assert.deepEqual([r.body.data.income, r.body.data.expense, r.body.data.profit], [50000, 23000, 27000]); assert.deepEqual(r.body.data.byCategory, { seeds: 12000, labour: 8000, transport: 3000 }); const carrot = r.body.data.crops.find((c) => c.cropType === "Carrot"); assert.deepEqual([carrot.income, carrot.expense, carrot.profit], [50000, 20000, 30000]); assert.equal(r.body.data.months.length, 1); ok("summary math is exact: income 50,000 − costs 23,000 = profit 27,000; Carrot profit 30,000; costs by category");
  const list = (await http("GET", "/ledger", { token: F12.token })).body.data; assert.equal(list.length, 4); assert.equal((await http("DELETE", `/ledger/${list[0].id}`, { token: F2.token })).status, 404); assert.equal((await http("DELETE", `/ledger/${list[0].id}`, { token: F12.token })).status, 200); assert.equal((await http("GET", "/ledger", { token: F12.token })).body.data.length, 3); assert.equal((await http("GET", "/ledger?cropType=Carrot", { token: F12.token })).body.data.length, 3); ok("entries can be filtered by crop; you can delete only your own");
  const dsum = (await http("GET", "/ledger/summary", { token: F.token })).body.data; assert.equal(dsum.income, 168000 + 40000); assert.equal(dsum.expense, 120400); assert.equal(dsum.entries, 9); ok("the demo farmer's seeded season: sales LKR 168,000 + the AgriLink order 40,000, costs 120,400");

  // ================= PRICE BOARD & ALERTS =================
  r = await http("GET", "/prices/board?market=Dambulla", { token: F.token }); assert.equal(r.status, 200); const tom = r.body.data.find((p) => p.cropType === "Tomato"); assert.equal(r.body.data.length, 12); assert.ok(tom.changePercent >= 15 && tom.changePercent <= 30, "tomato jump " + tom.changePercent); assert.equal(r.body.markets.length, 6); ok(`price board: 12 crops at Dambulla; Tomato ${tom.previousPricePerKg} → ${tom.pricePerKg} (${tom.changePercent > 0 ? "+" : ""}${tom.changePercent}%)`);
  r = await http("GET", "/prices/history/tomato?market=Dambulla&days=30", { token: F.token }); assert.equal(r.body.data.length, 10); assert.equal((await http("GET", "/prices/history/unobtainium", { token: F.token })).status, 400); ok("price history: 10 daily points; unknown crop refused");
  assert.equal((await http("POST", "/prices/report", { token: F1.token, body: { cropType: "Tomato", market: "Dambulla", pricePerKg: tom.pricePerKg + 10 } })).status, 201); assert.equal((await http("POST", "/prices/report", { token: F2.token, body: { cropType: "Tomato", market: "Dambulla", pricePerKg: tom.pricePerKg - 10 } })).status, 201); assert.equal((await http("POST", "/prices/report", { token: F1.token, body: { cropType: "Tomato", market: "Dambulla", pricePerKg: 5000 } })).body.code, "implausible"); assert.equal((await http("POST", "/prices/report", { token: F1.token, body: { cropType: "Tomato", market: "Atlantis", pricePerKg: 100 } })).status, 400); assert.equal((await http("POST", "/prices/report", { token: B.token, body: { cropType: "Tomato", market: "Dambulla", pricePerKg: 100 } })).status, 403); const b2 = (await http("GET", "/prices/board?market=Dambulla", { token: F.token })).body.data.find((p) => p.cropType === "Tomato"); assert.equal(b2.communityReports, 2); assert.equal(b2.communityMedian, tom.pricePerKg); assert.equal(b2.pricePerKg, tom.pricePerKg); ok("farmers report what they saw: 2 reports show as a community median next to (never replacing) the official price; wild guesses, bad markets and buyers refused");
  for (let i = 0; i < 9; i++) await http("POST", "/prices/report", { token: F12.token, body: { cropType: "Carrot", market: "Kandy", pricePerKg: 250 } }); r = await http("POST", "/prices/report", { token: F12.token, body: { cropType: "Carrot", market: "Kandy", pricePerKg: 250 } }); assert.equal(r.status, 201); assert.equal((await http("POST", "/prices/report", { token: F12.token, body: { cropType: "Carrot", market: "Kandy", pricePerKg: 250 } })).status, 429); ok("price reports are limited to 10 a day per farmer");
  r = await http("POST", "/prices/alerts", { token: F1.token, body: { cropType: "Carrot", direction: "below", thresholdLkr: 300, market: "Dambulla" } }); assert.equal(r.status, 201); const alertId = r.body.data._id; assert.equal((await http("POST", "/prices/alerts", { token: F1.token, body: { cropType: "Carrot", direction: "sideways", thresholdLkr: 300 } })).status, 400); assert.equal((await http("GET", "/prices/alerts", { token: F1.token })).body.data.length, 1); assert.equal((await http("GET", "/prices/alerts", { token: F.token })).body.data.length, 1); for (let i = 0; i < 10; i++) await http("POST", "/prices/alerts", { token: F2.token, body: { cropType: "Beans (Bush)", direction: "above", thresholdLkr: 400 + i } }); assert.equal((await http("POST", "/prices/alerts", { token: F2.token, body: { cropType: "Cabbage", direction: "above", thresholdLkr: 999 } })).body.code, "limit"); ok("alerts: created and listed privately; invalid direction refused; max 10 per farmer");
  assert.equal((await http("POST", "/admin/prices", { token: F.token, body: { market: "Dambulla", prices: [{ cropType: "Tomato", pricePerKg: 250 }] } })).status, 403); assert.equal((await http("POST", "/admin/prices", { token: ADMIN.token, body: { market: "Dambulla", prices: [{ cropType: "Unobtainium", pricePerKg: 250 }] } })).status, 400); assert.equal((await http("POST", "/admin/prices", { token: ADMIN.token, body: { market: "Dambulla", prices: [{ cropType: "Tomato", pricePerKg: -3 }] } })).status, 400);
  r = await http("POST", "/admin/prices", { token: ADMIN.token, body: { market: "Dambulla", prices: [{ cropType: "Tomato", pricePerKg: 330 }, { cropType: "Carrot", pricePerKg: 250 }] } }); assert.equal(r.status, 201); assert.equal(r.body.saved, 2); assert.ok(r.body.alertsTriggered >= 2, "alerts " + r.body.alertsTriggered); assert.ok(r.body.shockReminders >= 1); ok(`admin publishes today's prices (Tomato 330, Carrot 250): ${r.body.alertsTriggered} price alerts fired, ${r.body.shockReminders} 'market shock' notices sent to growers/sellers`);
  assert.ok(await Reminder.findOne({ farmer: F.id, type: "price_alert", title: /Tomato price alert/ })); assert.ok(await Reminder.findOne({ farmer: F1.id, type: "price_alert", title: /Carrot price alert/ })); assert.ok(await Reminder.findOne({ type: "price_alert", title: /Tomato price (jumped|dropped)/ })); r = await http("POST", "/admin/prices", { token: ADMIN.token, body: { market: "Dambulla", prices: [{ cropType: "Tomato", pricePerKg: 331 }, { cropType: "Carrot", pricePerKg: 251 }] } }); assert.equal(r.body.alertsTriggered, 0); assert.equal(r.body.shockReminders, 0); assert.equal((await http("GET", "/prices/board?market=Dambulla", { token: F.token })).body.data.filter((p) => p.cropType === "Tomato").length, 1); ok("each alert fires once a day (re-publishing the same day sends nothing again) and re-publishing replaces today's price instead of duplicating it");
  await http("DELETE", `/prices/alerts/${alertId}`, { token: F1.token }); assert.equal((await http("GET", "/prices/alerts", { token: F1.token })).body.data.length, 0); ok("alerts can be deleted");

  // ================= GROUP DIRECTORY =================
  r = await http("GET", "/group-chat/groups/directory", { token: F.token }); assert.equal(r.status, 200); assert.equal(r.body.data.districts.length, 25); assert.equal(r.body.data.crops.length, 51); assert.equal(r.body.data.all.key, "all"); assert.ok(r.body.data.districts.find((d) => d.key === "district:Kandy").memberCount >= 3); assert.equal(r.body.data.crops.find((c) => c.key === "crop:Tomato").joined, false); await http("POST", "/group-chat/groups/join", { token: F.token, body: { groupKey: "crop:Tomato" } }); assert.equal((await http("GET", "/group-chat/groups/directory", { token: F.token })).body.data.crops.find((c) => c.key === "crop:Tomato").joined, true); assert.equal((await http("GET", "/group-chat/groups/directory", { token: B.token })).status, 403); ok("group directory: 'All', all 25 districts and all 51 crops are always listed (even with 0 members) with member counts and a 'joined' flag — nothing to type, just tap to join");

  await User.deleteOne({ email: "admin.v4@agrilink.lk" }); await mongoose.disconnect();
  console.log(`\nALL ${passed} UPDATE-4 END-TO-END TESTS PASSED`);
})().catch(async (e) => { console.error("\nFAILED:", e.message); console.error((e.stack || "").split("\n").slice(1, 4).join("\n")); try { await mongoose.disconnect(); } catch (_) {} process.exit(1); });
